# Site settings
name: Firefox Marketplace DevHub Redesign Spec
title: Firefox Marketplace DevHub Redesign Spec
email: ehunt@mozilla.com
description: "Specifications for the eventual redesign of the Firefox Marketplace Developer Pages (devhub)"
# these need to be changed for each project
baseurl: "/devhub-redesign" #this is the github project name WITHOUT the trailing /
url: "https://marketplaceux.github.io"  #this the url of the GHPages account your project is hosted at

# Build settings
markdown: kramdown
permalinks: pretty
