$axure.loadCurrentPage({
  "url":"12_edit__categories.html",
  "generationDate":new Date(1399363416860.55),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"name"],
  "page":{
    "packageId":"685a0bda71d44fcd99c8e19aa6599caa",
    "type":"Axure:Page",
    "name":"12 edit, categories",
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"068958af0f4a497a9237fab6b8a2abc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE7E7E7},
            "size":{
              "width":2400,
              "height":2400},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afbd9078f47e46038c0a9b30d33e2b96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE7E7E7},
                "size":{
                  "width":2400,
                  "height":2400},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_my_submissions/u0.png"}},
{
          "id":"759bf3ea56384964b1eadf82c37a5d38",
          "label":"name text",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'FiraSansLight', 'Fira Sans Light', 'Fira Sans'",
            "fontSize":"20px",
            "fontWeight":"200",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":155,
              "y":92},
            "size":{
              "width":220,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8bf04baeb54465f9160c2c4822f440f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSansLight', 'Fira Sans Light', 'Fira Sans'",
                "fontSize":"20px",
                "fontWeight":"200",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":155,
                  "y":92},
                "size":{
                  "width":220,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc132b0a73d54b0587c02d89f77ee0fe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":75},
            "size":{
              "width":64,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"989760564cec4e25b23c1032b36f81b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":75},
                "size":{
                  "width":64,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u20.png"}},
{
          "id":"671966677935458fa98da54da8ab4b8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":170},
            "size":{
              "width":610,
              "height":410},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f54c3e67d2e409d81361c526d4552aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":170},
                "size":{
                  "width":610,
                  "height":410},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_categories/u2.png"}},
{
          "id":"eaadd83b76b54d678b6961faae966974",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":340,
              "y":190},
            "size":{
              "width":60,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e598cdbc6d0849a9b3f983ca68727789",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":340,
                  "y":190},
                "size":{
                  "width":60,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1af8c518ddfe452298965fc7872cddac",
          "label":"games",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":220},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"32d3adf21c7b43308312736595e2bcb9",
              "label":"selected",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3688d6ef99334b0e856481235590610b",
                  "label":"",
                  "parentDynamicPanel":"1af8c518ddfe452298965fc7872cddac",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":60,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8f65cb58919249af9a79a6e5753b0ef3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1af8c518ddfe452298965fc7872cddac",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":60,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set games to unselected",
                              "panelsToStates":[{
                                  "panelPath":["1af8c518ddfe452298965fc7872cddac"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/3_categories/u13.png"}},
{
                  "id":"8b2f0526f5dc46969235642d7469d274",
                  "label":"",
                  "parentDynamicPanel":"1af8c518ddfe452298965fc7872cddac",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":60},
                    "size":{
                      "width":40,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ba437c0dad8b49e79451a1c97ead59e8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1af8c518ddfe452298965fc7872cddac",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans', 'Fira Sans'",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":60},
                        "size":{
                          "width":40,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set games to unselected",
                              "panelsToStates":[{
                                  "panelPath":["1af8c518ddfe452298965fc7872cddac"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"c7109412d1504b3ca8b969a72d111d44",
              "label":"unselected",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a6de5f76bd9e4be8bdeb276496eeaef0",
                  "label":"",
                  "parentDynamicPanel":"1af8c518ddfe452298965fc7872cddac",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":60,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fe344867c5c54393803e591d9d9ea978",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1af8c518ddfe452298965fc7872cddac",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":60,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set games to selected",
                              "panelsToStates":[{
                                  "panelPath":["1af8c518ddfe452298965fc7872cddac"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/3_categories/u9.png"}},
{
                  "id":"384f3b04e4de4d77924c005ce1ca95f0",
                  "label":"",
                  "parentDynamicPanel":"1af8c518ddfe452298965fc7872cddac",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":9,
                      "y":60},
                    "size":{
                      "width":40,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bf3e54fb3eda440a9b5259ee9d371183",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1af8c518ddfe452298965fc7872cddac",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans', 'Fira Sans'",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":9,
                          "y":60},
                        "size":{
                          "width":40,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set games to selected",
                              "panelsToStates":[{
                                  "panelPath":["1af8c518ddfe452298965fc7872cddac"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"5a69656dced14412832426dca303922d",
          "label":"books",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":220},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"b1aae79459f2405c835d46df6449ea03",
              "label":"selected",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"781d9e602775432aab16c48cd33d8fd8",
                  "label":"",
                  "parentDynamicPanel":"5a69656dced14412832426dca303922d",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":60,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3513534b71b24437928b5936f199dd94",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5a69656dced14412832426dca303922d",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":60,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set books to unselected",
                              "panelsToStates":[{
                                  "panelPath":["5a69656dced14412832426dca303922d"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/3_categories/u22.png"}},
{
                  "id":"2e8a1f6e2ba94d96a9f32eb2f7551f3e",
                  "label":"",
                  "parentDynamicPanel":"5a69656dced14412832426dca303922d",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":11,
                      "y":60},
                    "size":{
                      "width":38,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"18eaf193ce224062a3f13d5a964b51c4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5a69656dced14412832426dca303922d",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans', 'Fira Sans'",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":11,
                          "y":60},
                        "size":{
                          "width":38,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set books to unselected",
                              "panelsToStates":[{
                                  "panelPath":["5a69656dced14412832426dca303922d"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"996a445018ca4459a2ed6d8cc3cb9659",
              "label":"unselected",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5dd48a1fc93b47bba52d29d5705828b4",
                  "label":"",
                  "parentDynamicPanel":"5a69656dced14412832426dca303922d",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":60,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a6e548602e3c4fe48b338cfe99f02d19",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5a69656dced14412832426dca303922d",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":60,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set books to selected",
                              "panelsToStates":[{
                                  "panelPath":["5a69656dced14412832426dca303922d"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"linkWindow",
                              "description":"Open 4 technical information in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"4_technical_information.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/3_categories/u18.png"}},
{
                  "id":"fd1d00a5f35340649ff4770ca1c1be10",
                  "label":"",
                  "parentDynamicPanel":"5a69656dced14412832426dca303922d",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":11,
                      "y":60},
                    "size":{
                      "width":38,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d08fb05eeb2845fca719fd253084f956",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5a69656dced14412832426dca303922d",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans', 'Fira Sans'",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":11,
                          "y":60},
                        "size":{
                          "width":38,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set books to selected",
                              "panelsToStates":[{
                                  "panelPath":["5a69656dced14412832426dca303922d"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"linkWindow",
                              "description":"Open 4 technical information in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"4_technical_information.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"0543855399794e6d90de727ac243fab2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":220},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f89992536d942c49b6958f8b8957b96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":220},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_categories/u26.png"}},
{
          "id":"f6c244fa14e94cc3a623e0d604b97b26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":544,
              "y":280},
            "size":{
              "width":54,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff29c23ffd944ee68cf1cdf0a6a7039d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":544,
                  "y":280},
                "size":{
                  "width":54,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aee1b41ef8f14ec0b42cf582b2855385",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":220},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bc9214d424b4a6886c608ff88bf3dd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":220},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_categories/u30.png"}},
{
          "id":"d7f2a4a561b74a31904b26516f08114e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":220},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd49b16faae346039718ab697b6f6f6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":220},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_categories/u32.png"}},
{
          "id":"c225f9518bb8429084be4ab9478f827b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":220},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67e2390255344caba9e708afbaf20f26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":840,
                  "y":220},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_categories/u34.png"}},
{
          "id":"5a8d826ef0f04208a6c59911e90ac0d3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":439,
              "y":330},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1653e4594074ec482eb81f2fa86e3c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":439,
                  "y":330},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_categories/u36.png"}},
{
          "id":"fc8296bd849b4ef185f9c75531af773d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":640,
              "y":280},
            "size":{
              "width":62,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc1edda446084bd4b9e1520cca94b8e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":640,
                  "y":280},
                "size":{
                  "width":62,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99bc4d7e72af457e89fda0ecabed66c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":726,
              "y":280},
            "size":{
              "width":88,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"633101320d6140329e63fc51f03474b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":726,
                  "y":280},
                "size":{
                  "width":88,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae066dfcd84c450da39453910586a0ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":836,
              "y":280},
            "size":{
              "width":67,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70581b3b3a694c37a045e7fbc58a26f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":836,
                  "y":280},
                "size":{
                  "width":67,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"681a926d2ffd4a98ab64e1833824d4b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":330},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83ae24ee83c54915af1c409eee04c8b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":330},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_categories/u44.png"}},
{
          "id":"a8c9d39c7ae44d9fa647ea547ee49b5f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":330},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"420e0eae350b4190967bd1b98dd0eb4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":330},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_categories/u46.png"}},
{
          "id":"aff81ef1d0784dc58dafb844b6976a9c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":330},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45b7b41ea920478296aa8f86ebfc3eeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":330},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_categories/u48.png"}},
{
          "id":"74bc6e7cde7e4828a5a1ec538a64da1b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":330},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecbd4facc12c4d038087169246055439",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":840,
                  "y":330},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_categories/u50.png"}},
{
          "id":"e68f1a4870ec4acca5aecb20bd25aeea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":436,
              "y":400},
            "size":{
              "width":66,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4450f388a934d4f99681a4ca22ca405",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":436,
                  "y":400},
                "size":{
                  "width":66,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"600e3441ffed4ff8a8f1dc89c357154c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":552,
              "y":400},
            "size":{
              "width":35,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f162d20fd7549b2a5e113e1c7989ba0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":552,
                  "y":400},
                "size":{
                  "width":35,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2aa163b769134773a5f6e2a41f758aab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":641,
              "y":400},
            "size":{
              "width":58,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aa2f9a64fca4ca5971067b16a0da6f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":641,
                  "y":400},
                "size":{
                  "width":58,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eaa87724bb7e49f4b687377b41a86757",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":740,
              "y":400},
            "size":{
              "width":62,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"310e52df90d949068e9aa09b985d3bb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":740,
                  "y":400},
                "size":{
                  "width":62,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c76a2002e9814fb3b3b6b95923bc16a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":833,
              "y":400},
            "size":{
              "width":74,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0afa823657e84049b01cc4a62860ef82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":833,
                  "y":400},
                "size":{
                  "width":74,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0403087b4db4a5cb83ca241e6217a46",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":460},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8d6f9668bac4205aa25fcc734b3d46b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":460},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_categories/u62.png"}},
{
          "id":"7c61d0d7ab324eecba320b841881c104",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":460},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4ea1dc61c4c4593adcbff2f3f71b836",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":460},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_categories/u64.png"}},
{
          "id":"caf459353c674dbd822c5d990c38f415",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":641,
              "y":460},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"310229b40e87456f8b7b5c49f8604211",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":641,
                  "y":460},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_categories/u32.png"}},
{
          "id":"456870154dc14a28a09f73c3f37766c4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":460},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b1a3f903e214a0580e8a8a78069bda2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":460},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_categories/u68.png"}},
{
          "id":"bdd6f9d65cfc430b8d4b3955ccbee345",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":460},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ee21a28d3cb4a4595da07b070732c77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":840,
                  "y":460},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_categories/u70.png"}},
{
          "id":"af02671ffa3d4796b2f7a1ed808742a8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":460},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43f47c8ad20d46ecbd26b7335344670f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":460},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_categories/u18.png"}},
{
          "id":"042206662c6845839fd9cd21c66392b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":340,
              "y":530},
            "size":{
              "width":60,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fabed0142e14693b508edb20258e21f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":340,
                  "y":530},
                "size":{
                  "width":60,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79b64fa3f1e4413482c71d92e1af7f11",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":330},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d96079a3517b49239c1d043af686ed90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":330},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_categories/u76.png"}},
{
          "id":"68670c52aa5746a393cda3ebea20aa14",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":344,
              "y":400},
            "size":{
              "width":51,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9b8d12aa12d4f7aa7668432c99742af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":344,
                  "y":400},
                "size":{
                  "width":51,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a67c0b53b7f548a796e648d7957fb4e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":440,
              "y":530},
            "size":{
              "width":59,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1edbfc93655943758c1ccb5c6e6a0d6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":530},
                "size":{
                  "width":59,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee6b52116005441ca3f1d2d09f613934",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":552,
              "y":530},
            "size":{
              "width":37,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a49d16ea0f54bcdaa4545a7b63c97df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":552,
                  "y":530},
                "size":{
                  "width":37,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f358b093c04d4b53b4b2e75de216cf64",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":651,
              "y":530},
            "size":{
              "width":40,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4af8973e2c4548e38547a4fec7f8cdd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":651,
                  "y":530},
                "size":{
                  "width":40,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c3d640bf64a408eac2b9fb9b6fd89d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":752,
              "y":530},
            "size":{
              "width":37,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2994bb25b70e4ec2b9da3f6db47c882a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":752,
                  "y":530},
                "size":{
                  "width":37,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8feb3f30a4c644ae922841e8994568b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":847,
              "y":530},
            "size":{
              "width":49,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c510c64567bc400a8a9f117de75501fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":847,
                  "y":530},
                "size":{
                  "width":49,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38313921882d498fa26a3135220ccc89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":80,
              "y":30},
            "size":{
              "width":300,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40d7bb1e4106431c8c2ed114625a7685",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":80,
                  "y":30},
                "size":{
                  "width":300,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 9 my submissions in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"9_my_submissions.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5f72168a2bf4a1c8ae52225ccdfd957",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "location":{
              "x":80,
              "y":170},
            "size":{
              "width":220,
              "height":280},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "linePattern":"none",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac4d3015398941cbbecb363ebfee1453",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "location":{
                  "x":80,
                  "y":170},
                "size":{
                  "width":220,
                  "height":280},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "linePattern":"none",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/10a_edit__manifest__version___publishing/u12.png"}},
{
          "id":"b24ec1e71d17496880181220568b4427",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":250},
            "size":{
              "width":220,
              "height":40},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa4903febd544b03a98d2f762ef725f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":250},
                "size":{
                  "width":220,
                  "height":40},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u122.png"}},
{
          "id":"0d45a00397374a74bfcd3ab7bc5725bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":220},
            "size":{
              "width":122,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82401f219ce34110a0cd007493914ffa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":220},
                "size":{
                  "width":122,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 11 edit, general information in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"11_edit__general_information.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c11cddf86bb847529923b71cc6ffc122",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":260},
            "size":{
              "width":64,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bba51dae4c10413dbbe13755edaad3f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":260},
                "size":{
                  "width":64,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49505b3cb64c4b0a91df856f71097539",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":300},
            "size":{
              "width":133,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26e14fa2a7d74aeb91a859aa3d8b55c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":300},
                "size":{
                  "width":133,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eabbd27d5b314eb9bf9c047d6b53e7d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":340},
            "size":{
              "width":91,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ca4372048d34eefa71bdcf72f0ec51e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":340},
                "size":{
                  "width":91,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32f87f15f4aa4c0ab73dfa347cf451f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":420},
            "size":{
              "width":128,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abb5a7a7af204b7ba64fc9fe9756d082",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":420},
                "size":{
                  "width":128,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf9732af60f6460b8c91da6804b1b13b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":380},
            "size":{
              "width":46,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c517f63f3104431a4aae66a342fdf6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":380},
                "size":{
                  "width":46,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"674750d603e04afaa7bcd34e1bfebca9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":180},
            "size":{
              "width":183,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e16f3fbbcd644769b950bfadf7e73e55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":180},
                "size":{
                  "width":183,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 10a edit, manifest, version &amp; publishing in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"10a_edit__manifest__version___publishing.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "068958af0f4a497a9237fab6b8a2abc0":{
      "scriptId":"u0"},
    "afbd9078f47e46038c0a9b30d33e2b96":{
      "scriptId":"u1"},
    "759bf3ea56384964b1eadf82c37a5d38":{
      "scriptId":"u2"},
    "c8bf04baeb54465f9160c2c4822f440f":{
      "scriptId":"u3"},
    "cc132b0a73d54b0587c02d89f77ee0fe":{
      "scriptId":"u4"},
    "989760564cec4e25b23c1032b36f81b1":{
      "scriptId":"u5"},
    "671966677935458fa98da54da8ab4b8e":{
      "scriptId":"u6"},
    "3f54c3e67d2e409d81361c526d4552aa":{
      "scriptId":"u7"},
    "eaadd83b76b54d678b6961faae966974":{
      "scriptId":"u8"},
    "e598cdbc6d0849a9b3f983ca68727789":{
      "scriptId":"u9"},
    "1af8c518ddfe452298965fc7872cddac":{
      "scriptId":"u10"},
    "3688d6ef99334b0e856481235590610b":{
      "scriptId":"u11"},
    "8f65cb58919249af9a79a6e5753b0ef3":{
      "scriptId":"u12"},
    "8b2f0526f5dc46969235642d7469d274":{
      "scriptId":"u13"},
    "ba437c0dad8b49e79451a1c97ead59e8":{
      "scriptId":"u14"},
    "a6de5f76bd9e4be8bdeb276496eeaef0":{
      "scriptId":"u15"},
    "fe344867c5c54393803e591d9d9ea978":{
      "scriptId":"u16"},
    "384f3b04e4de4d77924c005ce1ca95f0":{
      "scriptId":"u17"},
    "bf3e54fb3eda440a9b5259ee9d371183":{
      "scriptId":"u18"},
    "5a69656dced14412832426dca303922d":{
      "scriptId":"u19"},
    "781d9e602775432aab16c48cd33d8fd8":{
      "scriptId":"u20"},
    "3513534b71b24437928b5936f199dd94":{
      "scriptId":"u21"},
    "2e8a1f6e2ba94d96a9f32eb2f7551f3e":{
      "scriptId":"u22"},
    "18eaf193ce224062a3f13d5a964b51c4":{
      "scriptId":"u23"},
    "5dd48a1fc93b47bba52d29d5705828b4":{
      "scriptId":"u24"},
    "a6e548602e3c4fe48b338cfe99f02d19":{
      "scriptId":"u25"},
    "fd1d00a5f35340649ff4770ca1c1be10":{
      "scriptId":"u26"},
    "d08fb05eeb2845fca719fd253084f956":{
      "scriptId":"u27"},
    "0543855399794e6d90de727ac243fab2":{
      "scriptId":"u28"},
    "1f89992536d942c49b6958f8b8957b96":{
      "scriptId":"u29"},
    "f6c244fa14e94cc3a623e0d604b97b26":{
      "scriptId":"u30"},
    "ff29c23ffd944ee68cf1cdf0a6a7039d":{
      "scriptId":"u31"},
    "aee1b41ef8f14ec0b42cf582b2855385":{
      "scriptId":"u32"},
    "0bc9214d424b4a6886c608ff88bf3dd4":{
      "scriptId":"u33"},
    "d7f2a4a561b74a31904b26516f08114e":{
      "scriptId":"u34"},
    "fd49b16faae346039718ab697b6f6f6d":{
      "scriptId":"u35"},
    "c225f9518bb8429084be4ab9478f827b":{
      "scriptId":"u36"},
    "67e2390255344caba9e708afbaf20f26":{
      "scriptId":"u37"},
    "5a8d826ef0f04208a6c59911e90ac0d3":{
      "scriptId":"u38"},
    "f1653e4594074ec482eb81f2fa86e3c5":{
      "scriptId":"u39"},
    "fc8296bd849b4ef185f9c75531af773d":{
      "scriptId":"u40"},
    "fc1edda446084bd4b9e1520cca94b8e9":{
      "scriptId":"u41"},
    "99bc4d7e72af457e89fda0ecabed66c7":{
      "scriptId":"u42"},
    "633101320d6140329e63fc51f03474b5":{
      "scriptId":"u43"},
    "ae066dfcd84c450da39453910586a0ca":{
      "scriptId":"u44"},
    "70581b3b3a694c37a045e7fbc58a26f2":{
      "scriptId":"u45"},
    "681a926d2ffd4a98ab64e1833824d4b7":{
      "scriptId":"u46"},
    "83ae24ee83c54915af1c409eee04c8b9":{
      "scriptId":"u47"},
    "a8c9d39c7ae44d9fa647ea547ee49b5f":{
      "scriptId":"u48"},
    "420e0eae350b4190967bd1b98dd0eb4c":{
      "scriptId":"u49"},
    "aff81ef1d0784dc58dafb844b6976a9c":{
      "scriptId":"u50"},
    "45b7b41ea920478296aa8f86ebfc3eeb":{
      "scriptId":"u51"},
    "74bc6e7cde7e4828a5a1ec538a64da1b":{
      "scriptId":"u52"},
    "ecbd4facc12c4d038087169246055439":{
      "scriptId":"u53"},
    "e68f1a4870ec4acca5aecb20bd25aeea":{
      "scriptId":"u54"},
    "f4450f388a934d4f99681a4ca22ca405":{
      "scriptId":"u55"},
    "600e3441ffed4ff8a8f1dc89c357154c":{
      "scriptId":"u56"},
    "7f162d20fd7549b2a5e113e1c7989ba0":{
      "scriptId":"u57"},
    "2aa163b769134773a5f6e2a41f758aab":{
      "scriptId":"u58"},
    "0aa2f9a64fca4ca5971067b16a0da6f3":{
      "scriptId":"u59"},
    "eaa87724bb7e49f4b687377b41a86757":{
      "scriptId":"u60"},
    "310e52df90d949068e9aa09b985d3bb6":{
      "scriptId":"u61"},
    "c76a2002e9814fb3b3b6b95923bc16a2":{
      "scriptId":"u62"},
    "0afa823657e84049b01cc4a62860ef82":{
      "scriptId":"u63"},
    "e0403087b4db4a5cb83ca241e6217a46":{
      "scriptId":"u64"},
    "a8d6f9668bac4205aa25fcc734b3d46b":{
      "scriptId":"u65"},
    "7c61d0d7ab324eecba320b841881c104":{
      "scriptId":"u66"},
    "e4ea1dc61c4c4593adcbff2f3f71b836":{
      "scriptId":"u67"},
    "caf459353c674dbd822c5d990c38f415":{
      "scriptId":"u68"},
    "310229b40e87456f8b7b5c49f8604211":{
      "scriptId":"u69"},
    "456870154dc14a28a09f73c3f37766c4":{
      "scriptId":"u70"},
    "6b1a3f903e214a0580e8a8a78069bda2":{
      "scriptId":"u71"},
    "bdd6f9d65cfc430b8d4b3955ccbee345":{
      "scriptId":"u72"},
    "8ee21a28d3cb4a4595da07b070732c77":{
      "scriptId":"u73"},
    "af02671ffa3d4796b2f7a1ed808742a8":{
      "scriptId":"u74"},
    "43f47c8ad20d46ecbd26b7335344670f":{
      "scriptId":"u75"},
    "042206662c6845839fd9cd21c66392b2":{
      "scriptId":"u76"},
    "3fabed0142e14693b508edb20258e21f":{
      "scriptId":"u77"},
    "79b64fa3f1e4413482c71d92e1af7f11":{
      "scriptId":"u78"},
    "d96079a3517b49239c1d043af686ed90":{
      "scriptId":"u79"},
    "68670c52aa5746a393cda3ebea20aa14":{
      "scriptId":"u80"},
    "b9b8d12aa12d4f7aa7668432c99742af":{
      "scriptId":"u81"},
    "a67c0b53b7f548a796e648d7957fb4e4":{
      "scriptId":"u82"},
    "1edbfc93655943758c1ccb5c6e6a0d6e":{
      "scriptId":"u83"},
    "ee6b52116005441ca3f1d2d09f613934":{
      "scriptId":"u84"},
    "9a49d16ea0f54bcdaa4545a7b63c97df":{
      "scriptId":"u85"},
    "f358b093c04d4b53b4b2e75de216cf64":{
      "scriptId":"u86"},
    "4af8973e2c4548e38547a4fec7f8cdd7":{
      "scriptId":"u87"},
    "6c3d640bf64a408eac2b9fb9b6fd89d7":{
      "scriptId":"u88"},
    "2994bb25b70e4ec2b9da3f6db47c882a":{
      "scriptId":"u89"},
    "8feb3f30a4c644ae922841e8994568b6":{
      "scriptId":"u90"},
    "c510c64567bc400a8a9f117de75501fc":{
      "scriptId":"u91"},
    "38313921882d498fa26a3135220ccc89":{
      "scriptId":"u92"},
    "40d7bb1e4106431c8c2ed114625a7685":{
      "scriptId":"u93"},
    "c5f72168a2bf4a1c8ae52225ccdfd957":{
      "scriptId":"u94"},
    "ac4d3015398941cbbecb363ebfee1453":{
      "scriptId":"u95"},
    "b24ec1e71d17496880181220568b4427":{
      "scriptId":"u96"},
    "aa4903febd544b03a98d2f762ef725f4":{
      "scriptId":"u97"},
    "0d45a00397374a74bfcd3ab7bc5725bd":{
      "scriptId":"u98"},
    "82401f219ce34110a0cd007493914ffa":{
      "scriptId":"u99"},
    "c11cddf86bb847529923b71cc6ffc122":{
      "scriptId":"u100"},
    "bba51dae4c10413dbbe13755edaad3f4":{
      "scriptId":"u101"},
    "49505b3cb64c4b0a91df856f71097539":{
      "scriptId":"u102"},
    "26e14fa2a7d74aeb91a859aa3d8b55c0":{
      "scriptId":"u103"},
    "eabbd27d5b314eb9bf9c047d6b53e7d3":{
      "scriptId":"u104"},
    "5ca4372048d34eefa71bdcf72f0ec51e":{
      "scriptId":"u105"},
    "32f87f15f4aa4c0ab73dfa347cf451f0":{
      "scriptId":"u106"},
    "abb5a7a7af204b7ba64fc9fe9756d082":{
      "scriptId":"u107"},
    "bf9732af60f6460b8c91da6804b1b13b":{
      "scriptId":"u108"},
    "1c517f63f3104431a4aae66a342fdf6c":{
      "scriptId":"u109"},
    "674750d603e04afaa7bcd34e1bfebca9":{
      "scriptId":"u110"},
    "e16f3fbbcd644769b950bfadf7e73e55":{
      "scriptId":"u111"}}});