$axure.loadCurrentPage({
  "url":"8_confirmation.html",
  "generationDate":new Date(1399021344978.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"name"],
  "page":{
    "packageId":"8015b6985c5643ebb23e01ac2ec8e414",
    "type":"Axure:Page",
    "name":"8 confirmation",
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"068958af0f4a497a9237fab6b8a2abc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE7E7E7},
            "size":{
              "width":2400,
              "height":2400},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afbd9078f47e46038c0a9b30d33e2b96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE7E7E7},
                "size":{
                  "width":2400,
                  "height":2400},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_my_submissions/u0.png"}},
{
          "id":"8cbca923fff64ea7b93d1340cc06b094",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "location":{
              "x":80,
              "y":80},
            "size":{
              "width":220,
              "height":320},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "linePattern":"none",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33adcd41d60d426595fe5ad7681d07ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "location":{
                  "x":80,
                  "y":80},
                "size":{
                  "width":220,
                  "height":320},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "linePattern":"none",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_upload_manifest/u6.png"}},
{
          "id":"07d13ae2cd364d9ab6a8a3d663819588",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":360},
            "size":{
              "width":220,
              "height":40},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "linePattern":"none",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b128e37d41044207b9fb17bfadba364d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":360},
                "size":{
                  "width":220,
                  "height":40},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "linePattern":"none",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/8_confirmation/u4.png"}},
{
          "id":"f0f845764dbf4e939eca90558ea7a0cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":90},
            "size":{
              "width":52,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f802f797900e4dffb089daeadd6516a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":90},
                "size":{
                  "width":52,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a188e09d8e54638ade6047297f1dd15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":130},
            "size":{
              "width":122,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60499b8c89fc4e978e52ec7bac138b82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":130},
                "size":{
                  "width":122,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8472beb9dc14100a326a468e74ef3b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":170},
            "size":{
              "width":64,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"185f666df82f4e4ea258f3832338418a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":170},
                "size":{
                  "width":64,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57083c9cb90148cc880e619c0e2595c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":210},
            "size":{
              "width":133,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"907af02152d74b0c8a029441dbc18592",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":210},
                "size":{
                  "width":133,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cfe5e2110bd41bd85b9923d097c173f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":250},
            "size":{
              "width":91,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"291c857fcb0243bba052d5880f5c4cf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":250},
                "size":{
                  "width":91,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fe2d97b988240df878c9ce2152945e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":330},
            "size":{
              "width":128,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5575df7ae7c144d197290e689ebb0663",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":330},
                "size":{
                  "width":128,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e42b8fdaa29c4d78a4ef7fa831c6deff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":370},
            "size":{
              "width":80,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1a0407989de465983be9d1a22a17f34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":370},
                "size":{
                  "width":80,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57e0395d671443d486b9d148ca4f81c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":290},
            "size":{
              "width":46,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c555c9f819204355925af867e320ff9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":290},
                "size":{
                  "width":46,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0dc8c59f7b24ab18bc164ed519ad040",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":80},
            "size":{
              "width":320,
              "height":1145},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95a7981c68664f5499d37cfc87a8d04b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":80},
                "size":{
                  "width":320,
                  "height":1145},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u2.png"}},
{
          "id":"9029bdcdd3344d7dba7f771cd596e2a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSansMedium', 'Fira Sans Medium', 'Fira Sans'",
            "fontSize":"15px",
            "fontWeight":"500",
            "location":{
              "x":570,
              "y":1005},
            "size":{
              "width":300,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68eedcd5162045d68a8071169a090b42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSansMedium', 'Fira Sans Medium', 'Fira Sans'",
                "fontSize":"15px",
                "fontWeight":"500",
                "location":{
                  "x":570,
                  "y":1005},
                "size":{
                  "width":300,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0194f92c7b8048678a54cb221175ef34",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA7A7A7,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":650,
              "y":122},
            "size":{
              "width":54,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e4bf95dc2c244b895ec59873a750bb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA7A7A7,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":650,
                  "y":122},
                "size":{
                  "width":54,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96446c1560c0435c8f39e2a56d5a0164",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA7A7A7,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":650,
              "y":137},
            "size":{
              "width":63,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8837ed7be16d430fb1d2c280bd0de9b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA7A7A7,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":650,
                  "y":137},
                "size":{
                  "width":63,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc7374a8a0d74d7c84de4ee7c2d3ebf1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":1050},
            "size":{
              "width":57,
              "height":77}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d59f66f87f224051ab35e1b6fba1fb89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":1050},
                "size":{
                  "width":57,
                  "height":77}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/8_confirmation/u30.png"}},
{
          "id":"f9b671b2b33841778e581cf492e8d7f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "location":{
              "x":560,
              "y":175},
            "size":{
              "width":320,
              "height":230},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d8291d24eef49069867e448fcf906d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "location":{
                  "x":560,
                  "y":175},
                "size":{
                  "width":320,
                  "height":230},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u8.png"}},
{
          "id":"e1aea06444a94dc085447ff58a85b07a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":175},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0679a1926d144ed8ef625e6b639f753",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":175},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u10.png"}},
{
          "id":"022a55fb0dfc4f6a9f99ce9b5347fbba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSansMedium', 'Fira Sans Medium', 'Fira Sans'",
            "fontSize":"15px",
            "fontWeight":"500",
            "location":{
              "x":570,
              "y":420},
            "size":{
              "width":300,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30be6132d3c542339cb8bc17acbf5314",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSansMedium', 'Fira Sans Medium', 'Fira Sans'",
                "fontSize":"15px",
                "fontWeight":"500",
                "location":{
                  "x":570,
                  "y":420},
                "size":{
                  "width":300,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21e52d27bcfc4a9a84cf13fad02c3b63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSansMedium', 'Fira Sans Medium', 'Fira Sans'",
            "fontSize":"15px",
            "location":{
              "x":570,
              "y":760},
            "size":{
              "width":300,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f19539428acb4ec28c24bf6fd09c940b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSansMedium', 'Fira Sans Medium', 'Fira Sans'",
                "fontSize":"15px",
                "location":{
                  "x":570,
                  "y":760},
                "size":{
                  "width":300,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6072492936243ce90949f45f10a3359",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":820},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/2a_screenshot/u16_line.png"}},
{
          "id":"f51773d25ca14f8ebd99b2c79320803f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":975},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/2a_screenshot/u16_line.png"}},
{
          "id":"9ee575caa5a9460fba0e060191530e59",
          "label":"name text",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'FiraSansLight', 'Fira Sans Light', 'Fira Sans'",
            "fontSize":"20px",
            "fontWeight":"200",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":650,
              "y":97},
            "size":{
              "width":220,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e81659fa18ea4116bb72008710ca7aea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSansLight', 'Fira Sans Light', 'Fira Sans'",
                "fontSize":"20px",
                "fontWeight":"200",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":650,
                  "y":97},
                "size":{
                  "width":220,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64482bcf981d48128ae4179d78b48220",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":575,
              "y":95},
            "size":{
              "width":64,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2f91bdf7c1b4064aff369d04dafbe51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":575,
                  "y":95},
                "size":{
                  "width":64,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u20.png"}},
{
          "id":"8251b17cc2e14b959c3f86bc675ed06f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":210},
            "size":{
              "width":100,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e822e94aa5742beb99330f1b416580d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":210},
                "size":{
                  "width":100,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u74.png"}},
{
          "id":"0f143846294841cd9153069cea61d1d3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":210},
            "size":{
              "width":100,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afc4cbc9cac5446abc096bdb2dfcaf95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":670,
                  "y":210},
                "size":{
                  "width":100,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u50.png"}},
{
          "id":"955be442d75b4b2f92dfc4dff2a81133",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":210},
            "size":{
              "width":100,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e258b5a61f2040a5953131391f59b17e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":210},
                "size":{
                  "width":100,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u32.png"}},
{
          "id":"c5927115c46944e2bd840b7d11283dd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":734,
              "y":375},
            "size":{
              "width":13,
              "height":13},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37eb2ecd68f948edb55828565145c87d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":734,
                  "y":375},
                "size":{
                  "width":13,
                  "height":13},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u92.png"}},
{
          "id":"4a73847916aa4b7ab9dbf496053bf0cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":714,
              "y":375},
            "size":{
              "width":13,
              "height":13},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebf484b71d4a4d21af6c2324e0c613ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":714,
                  "y":375},
                "size":{
                  "width":13,
                  "height":13},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u94.png"}},
{
          "id":"3b9e11c6f9a24a4e946e4b23ab418fd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":694,
              "y":375},
            "size":{
              "width":13,
              "height":13},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41b4c401240d4c7cb66d24415b936e7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":694,
                  "y":375},
                "size":{
                  "width":13,
                  "height":13},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u94.png"}},
{
          "id":"d885aae30b5b41e68bc6f6af85112c30",
          "label":"description text",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":570,
              "y":448},
            "size":{
              "width":300,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"560f203581ff46c7b942d71be35c6030",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":570,
                  "y":448},
                "size":{
                  "width":300,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"322f7c60631044a6861e29b9a9e24441",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF4CB1FF},
{
                  "color":0xFF4CB1FF},
{
                  "color":0xFF1793E5},
{
                  "color":0xFF1793E5}]},
            "location":{
              "x":780,
              "y":137},
            "size":{
              "width":90,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF1793E5},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cd80b2cadd24508b908de57692410b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF4CB1FF},
{
                      "color":0xFF4CB1FF},
{
                      "color":0xFF1793E5},
{
                      "color":0xFF1793E5}]},
                "location":{
                  "x":780,
                  "y":137},
                "size":{
                  "width":90,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF1793E5},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/8_confirmation/u60.png"}},
{
          "id":"51e36e602e054b598f98ff2ee0c58b8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "location":{
              "x":320,
              "y":80},
            "size":{
              "width":220,
              "height":135},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "linePattern":"none",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82cd5cd59efe4c558131445adcd519ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "location":{
                  "x":320,
                  "y":80},
                "size":{
                  "width":220,
                  "height":135},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "linePattern":"none",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u120.png"}},
{
          "id":"43158c1a9f2647a7aa28609814f6c74c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":130},
            "size":{
              "width":220,
              "height":40},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33356ae67b514283a2344e64e5278a34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":130},
                "size":{
                  "width":220,
                  "height":40},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u122.png"}},
{
          "id":"e43bdbaeea9c4c18bc702bceca99c3cb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":125},
            "size":{
              "width":220,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/2a_screenshot/u124_line.png"}},
{
          "id":"cd24883c030b479fb99d886daa427553",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":335,
              "y":140},
            "size":{
              "width":45,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"668b8f2818624741b4cdd1d9cf5774db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":335,
                  "y":140},
                "size":{
                  "width":45,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59c2d72315874d678045bdd95fb5c392",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"11px",
            "horizontalAlignment":"right",
            "location":{
              "x":488,
              "y":142},
            "size":{
              "width":37,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aef21c53b4024db281075d542af69db6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"11px",
                "horizontalAlignment":"right",
                "location":{
                  "x":488,
                  "y":142},
                "size":{
                  "width":37,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efd3ed74419143abba596153e4ea0444",
          "label":"description text",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":570,
              "y":700},
            "size":{
              "width":300,
              "height":50},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9e3775cbd934f9b97f7942cf305501d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":570,
                  "y":700},
                "size":{
                  "width":300,
                  "height":50},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/description_text_u129.png"}},
{
          "id":"e211893f816047d2b559e676720358ff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":706,
              "y":711},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e531b4f362d249889404c12c5e4380c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":706,
                  "y":711},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u106.png"}},
{
          "id":"a89059436f9042f281429e6a80b04a16",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":645,
              "y":713},
            "size":{
              "width":53,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e768b24d95a240f2bc663f1f9a240cb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":645,
                  "y":713},
                "size":{
                  "width":53,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52f95200fd934ec29c9309bc362bdf98",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":743,
              "y":713},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf58291f238440c89bcad316de52150f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":743,
                  "y":713},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8d880f697254ca395f8eff8528d319a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSansMedium', 'Fira Sans Medium', 'Fira Sans'",
            "fontSize":"15px",
            "fontWeight":"500",
            "location":{
              "x":335,
              "y":95},
            "size":{
              "width":74,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ec9b1a05b0e4717aedc26383e0cd4e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSansMedium', 'Fira Sans Medium', 'Fira Sans'",
                "fontSize":"15px",
                "fontWeight":"500",
                "location":{
                  "x":335,
                  "y":95},
                "size":{
                  "width":74,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbc2f10822364345ad2ae17369e4e2ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":335,
              "y":180},
            "size":{
              "width":103,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59d11741eaff41399f316f18c9f7f29e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":335,
                  "y":180},
                "size":{
                  "width":103,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ad1ae29f4a84ab699ee474abb1eb133",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF4CB1FF},
{
                  "color":0xFF4CB1FF},
{
                  "color":0xFF1793E5},
{
                  "color":0xFF1793E5}]},
            "location":{
              "x":770,
              "y":1248},
            "size":{
              "width":110,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF1793E5},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ed93284c5684b239a4f38d4fa939ed0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF4CB1FF},
{
                      "color":0xFF4CB1FF},
{
                      "color":0xFF1793E5},
{
                      "color":0xFF1793E5}]},
                "location":{
                  "x":770,
                  "y":1248},
                "size":{
                  "width":110,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF1793E5},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 9 my submissions in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"9_my_submissions.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/8_confirmation/u83.png"}},
{
          "id":"0f13ba47f3d042a2915db91a71aee318",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF4CB1FF},
{
                  "color":0xFF4CB1FF},
{
                  "color":0xFF1793E5},
{
                  "color":0xFF1793E5}]},
            "location":{
              "x":320,
              "y":1255},
            "size":{
              "width":160,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF1793E5},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4d1787123f446a88c42ec1ecf5885f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF4CB1FF},
{
                      "color":0xFF4CB1FF},
{
                      "color":0xFF1793E5},
{
                      "color":0xFF1793E5}]},
                "location":{
                  "x":320,
                  "y":1255},
                "size":{
                  "width":160,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF1793E5},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 7d payment account in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"7d_payment_account.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/2a_screenshot/u143.png"}},
{
          "id":"21a99014f5264faa989fbdc877193c69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5F5F5F,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFE7E7E7},
{
                  "color":0xFFE7E7E7}]},
            "location":{
              "x":570,
              "y":850},
            "size":{
              "width":145,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5118c8ba0f95423fb1031f368fa042b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5F5F5F,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFE7E7E7},
{
                      "color":0xFFE7E7E7}]},
                "location":{
                  "x":570,
                  "y":850},
                "size":{
                  "width":145,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2c_support_email/u114.png"}},
{
          "id":"3de9d47022644b99911a219562392604",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5F5F5F,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFE7E7E7},
{
                  "color":0xFFE7E7E7}]},
            "location":{
              "x":725,
              "y":850},
            "size":{
              "width":145,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8753b4b27634752be62e3d9fcb7cebb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5F5F5F,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFE7E7E7},
{
                      "color":0xFFE7E7E7}]},
                "location":{
                  "x":725,
                  "y":850},
                "size":{
                  "width":145,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2c_support_email/u114.png"}},
{
          "id":"2a7f7c6b062f4b329ca52cb88904bf7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5F5F5F,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFE7E7E7},
{
                  "color":0xFFE7E7E7}]},
            "location":{
              "x":570,
              "y":910},
            "size":{
              "width":145,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b6fe63177cd45ad9c3d2b8324d972d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5F5F5F,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFE7E7E7},
{
                      "color":0xFFE7E7E7}]},
                "location":{
                  "x":570,
                  "y":910},
                "size":{
                  "width":145,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2c_support_email/u114.png"}},
{
          "id":"02a838b30bd34350b160ef2ad57fa6d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5F5F5F,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFE7E7E7},
{
                  "color":0xFFE7E7E7}]},
            "location":{
              "x":725,
              "y":910},
            "size":{
              "width":145,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"790e7fe7afb949b2bc4b0d0debc8c657",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5F5F5F,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFE7E7E7},
{
                      "color":0xFFE7E7E7}]},
                "location":{
                  "x":725,
                  "y":910},
                "size":{
                  "width":145,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2c_support_email/u114.png"}},
{
          "id":"f2d4893ebcf94b4d9b4cbb035e32c0f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF4CB1FF},
{
                  "color":0xFF4CB1FF},
{
                  "color":0xFF1793E5},
{
                  "color":0xFF1793E5}]},
            "location":{
              "x":620,
              "y":1255},
            "size":{
              "width":130,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF1793E5},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40c10c595c2a4967bb71e7dcb2831df4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF4CB1FF},
{
                      "color":0xFF4CB1FF},
{
                      "color":0xFF1793E5},
{
                      "color":0xFF1793E5}]},
                "location":{
                  "x":620,
                  "y":1255},
                "size":{
                  "width":130,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF1793E5},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 9 my submissions in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"9_my_submissions.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/8_confirmation/u95.png"}},
{
          "id":"5a3161d367ea45f5b6a3c27ba75b0023",
          "label":"icon-tooltip",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":394,
              "y":15},
            "size":{
              "width":390,
              "height":48},
            "cornerRadiusTopLeft":"5",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d8939a6c46d4a07a433c99708fe56bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":394,
                  "y":15},
                "size":{
                  "width":390,
                  "height":48},
                "cornerRadiusTopLeft":"5",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/8_confirmation/icon-tooltip_u97.png"}},
{
          "id":"533cce8592c841d89eb86a9040e7adc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":80,
              "y":30},
            "size":{
              "width":232,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"863e1e55e4034bc080b40ab537789cf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":80,
                  "y":30},
                "size":{
                  "width":232,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 9 my submissions in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"9_my_submissions.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "068958af0f4a497a9237fab6b8a2abc0":{
      "scriptId":"u0"},
    "afbd9078f47e46038c0a9b30d33e2b96":{
      "scriptId":"u1"},
    "8cbca923fff64ea7b93d1340cc06b094":{
      "scriptId":"u2"},
    "33adcd41d60d426595fe5ad7681d07ba":{
      "scriptId":"u3"},
    "07d13ae2cd364d9ab6a8a3d663819588":{
      "scriptId":"u4"},
    "b128e37d41044207b9fb17bfadba364d":{
      "scriptId":"u5"},
    "f0f845764dbf4e939eca90558ea7a0cb":{
      "scriptId":"u6"},
    "f802f797900e4dffb089daeadd6516a5":{
      "scriptId":"u7"},
    "7a188e09d8e54638ade6047297f1dd15":{
      "scriptId":"u8"},
    "60499b8c89fc4e978e52ec7bac138b82":{
      "scriptId":"u9"},
    "c8472beb9dc14100a326a468e74ef3b1":{
      "scriptId":"u10"},
    "185f666df82f4e4ea258f3832338418a":{
      "scriptId":"u11"},
    "57083c9cb90148cc880e619c0e2595c5":{
      "scriptId":"u12"},
    "907af02152d74b0c8a029441dbc18592":{
      "scriptId":"u13"},
    "4cfe5e2110bd41bd85b9923d097c173f":{
      "scriptId":"u14"},
    "291c857fcb0243bba052d5880f5c4cf4":{
      "scriptId":"u15"},
    "7fe2d97b988240df878c9ce2152945e8":{
      "scriptId":"u16"},
    "5575df7ae7c144d197290e689ebb0663":{
      "scriptId":"u17"},
    "e42b8fdaa29c4d78a4ef7fa831c6deff":{
      "scriptId":"u18"},
    "c1a0407989de465983be9d1a22a17f34":{
      "scriptId":"u19"},
    "57e0395d671443d486b9d148ca4f81c0":{
      "scriptId":"u20"},
    "c555c9f819204355925af867e320ff9d":{
      "scriptId":"u21"},
    "a0dc8c59f7b24ab18bc164ed519ad040":{
      "scriptId":"u22"},
    "95a7981c68664f5499d37cfc87a8d04b":{
      "scriptId":"u23"},
    "9029bdcdd3344d7dba7f771cd596e2a6":{
      "scriptId":"u24"},
    "68eedcd5162045d68a8071169a090b42":{
      "scriptId":"u25"},
    "0194f92c7b8048678a54cb221175ef34":{
      "scriptId":"u26"},
    "0e4bf95dc2c244b895ec59873a750bb1":{
      "scriptId":"u27"},
    "96446c1560c0435c8f39e2a56d5a0164":{
      "scriptId":"u28"},
    "8837ed7be16d430fb1d2c280bd0de9b6":{
      "scriptId":"u29"},
    "dc7374a8a0d74d7c84de4ee7c2d3ebf1":{
      "scriptId":"u30"},
    "d59f66f87f224051ab35e1b6fba1fb89":{
      "scriptId":"u31"},
    "f9b671b2b33841778e581cf492e8d7f2":{
      "scriptId":"u32"},
    "3d8291d24eef49069867e448fcf906d0":{
      "scriptId":"u33"},
    "e1aea06444a94dc085447ff58a85b07a":{
      "scriptId":"u34"},
    "e0679a1926d144ed8ef625e6b639f753":{
      "scriptId":"u35"},
    "022a55fb0dfc4f6a9f99ce9b5347fbba":{
      "scriptId":"u36"},
    "30be6132d3c542339cb8bc17acbf5314":{
      "scriptId":"u37"},
    "21e52d27bcfc4a9a84cf13fad02c3b63":{
      "scriptId":"u38"},
    "f19539428acb4ec28c24bf6fd09c940b":{
      "scriptId":"u39"},
    "b6072492936243ce90949f45f10a3359":{
      "scriptId":"u40"},
    "f51773d25ca14f8ebd99b2c79320803f":{
      "scriptId":"u41"},
    "9ee575caa5a9460fba0e060191530e59":{
      "scriptId":"u42"},
    "e81659fa18ea4116bb72008710ca7aea":{
      "scriptId":"u43"},
    "64482bcf981d48128ae4179d78b48220":{
      "scriptId":"u44"},
    "d2f91bdf7c1b4064aff369d04dafbe51":{
      "scriptId":"u45"},
    "8251b17cc2e14b959c3f86bc675ed06f":{
      "scriptId":"u46"},
    "1e822e94aa5742beb99330f1b416580d":{
      "scriptId":"u47"},
    "0f143846294841cd9153069cea61d1d3":{
      "scriptId":"u48"},
    "afc4cbc9cac5446abc096bdb2dfcaf95":{
      "scriptId":"u49"},
    "955be442d75b4b2f92dfc4dff2a81133":{
      "scriptId":"u50"},
    "e258b5a61f2040a5953131391f59b17e":{
      "scriptId":"u51"},
    "c5927115c46944e2bd840b7d11283dd2":{
      "scriptId":"u52"},
    "37eb2ecd68f948edb55828565145c87d":{
      "scriptId":"u53"},
    "4a73847916aa4b7ab9dbf496053bf0cc":{
      "scriptId":"u54"},
    "ebf484b71d4a4d21af6c2324e0c613ac":{
      "scriptId":"u55"},
    "3b9e11c6f9a24a4e946e4b23ab418fd2":{
      "scriptId":"u56"},
    "41b4c401240d4c7cb66d24415b936e7d":{
      "scriptId":"u57"},
    "d885aae30b5b41e68bc6f6af85112c30":{
      "scriptId":"u58"},
    "560f203581ff46c7b942d71be35c6030":{
      "scriptId":"u59"},
    "322f7c60631044a6861e29b9a9e24441":{
      "scriptId":"u60"},
    "1cd80b2cadd24508b908de57692410b3":{
      "scriptId":"u61"},
    "51e36e602e054b598f98ff2ee0c58b8f":{
      "scriptId":"u62"},
    "82cd5cd59efe4c558131445adcd519ba":{
      "scriptId":"u63"},
    "43158c1a9f2647a7aa28609814f6c74c":{
      "scriptId":"u64"},
    "33356ae67b514283a2344e64e5278a34":{
      "scriptId":"u65"},
    "e43bdbaeea9c4c18bc702bceca99c3cb":{
      "scriptId":"u66"},
    "cd24883c030b479fb99d886daa427553":{
      "scriptId":"u67"},
    "668b8f2818624741b4cdd1d9cf5774db":{
      "scriptId":"u68"},
    "59c2d72315874d678045bdd95fb5c392":{
      "scriptId":"u69"},
    "aef21c53b4024db281075d542af69db6":{
      "scriptId":"u70"},
    "efd3ed74419143abba596153e4ea0444":{
      "scriptId":"u71"},
    "d9e3775cbd934f9b97f7942cf305501d":{
      "scriptId":"u72"},
    "e211893f816047d2b559e676720358ff":{
      "scriptId":"u73"},
    "e531b4f362d249889404c12c5e4380c7":{
      "scriptId":"u74"},
    "a89059436f9042f281429e6a80b04a16":{
      "scriptId":"u75"},
    "e768b24d95a240f2bc663f1f9a240cb6":{
      "scriptId":"u76"},
    "52f95200fd934ec29c9309bc362bdf98":{
      "scriptId":"u77"},
    "cf58291f238440c89bcad316de52150f":{
      "scriptId":"u78"},
    "d8d880f697254ca395f8eff8528d319a":{
      "scriptId":"u79"},
    "7ec9b1a05b0e4717aedc26383e0cd4e1":{
      "scriptId":"u80"},
    "dbc2f10822364345ad2ae17369e4e2ad":{
      "scriptId":"u81"},
    "59d11741eaff41399f316f18c9f7f29e":{
      "scriptId":"u82"},
    "5ad1ae29f4a84ab699ee474abb1eb133":{
      "scriptId":"u83"},
    "3ed93284c5684b239a4f38d4fa939ed0":{
      "scriptId":"u84"},
    "0f13ba47f3d042a2915db91a71aee318":{
      "scriptId":"u85"},
    "f4d1787123f446a88c42ec1ecf5885f9":{
      "scriptId":"u86"},
    "21a99014f5264faa989fbdc877193c69":{
      "scriptId":"u87"},
    "5118c8ba0f95423fb1031f368fa042b8":{
      "scriptId":"u88"},
    "3de9d47022644b99911a219562392604":{
      "scriptId":"u89"},
    "f8753b4b27634752be62e3d9fcb7cebb":{
      "scriptId":"u90"},
    "2a7f7c6b062f4b329ca52cb88904bf7e":{
      "scriptId":"u91"},
    "1b6fe63177cd45ad9c3d2b8324d972d7":{
      "scriptId":"u92"},
    "02a838b30bd34350b160ef2ad57fa6d1":{
      "scriptId":"u93"},
    "790e7fe7afb949b2bc4b0d0debc8c657":{
      "scriptId":"u94"},
    "f2d4893ebcf94b4d9b4cbb035e32c0f7":{
      "scriptId":"u95"},
    "40c10c595c2a4967bb71e7dcb2831df4":{
      "scriptId":"u96"},
    "5a3161d367ea45f5b6a3c27ba75b0023":{
      "scriptId":"u97"},
    "7d8939a6c46d4a07a433c99708fe56bd":{
      "scriptId":"u98"},
    "533cce8592c841d89eb86a9040e7adc1":{
      "scriptId":"u99"},
    "863e1e55e4034bc080b40ab537789cf1":{
      "scriptId":"u100"}}});