$axure.loadCurrentPage({
  "url":"10b_submitted.html",
  "generationDate":new Date(1399363411722.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"name"],
  "page":{
    "packageId":"a0a5a98ceeab4b4388ed41dca4cbcf46",
    "type":"Axure:Page",
    "name":"10b submitted",
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"068958af0f4a497a9237fab6b8a2abc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE7E7E7},
            "size":{
              "width":2400,
              "height":2400},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afbd9078f47e46038c0a9b30d33e2b96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE7E7E7},
                "size":{
                  "width":2400,
                  "height":2400},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_my_submissions/u0.png"}},
{
          "id":"759bf3ea56384964b1eadf82c37a5d38",
          "label":"name text",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'FiraSansLight', 'Fira Sans Light', 'Fira Sans'",
            "fontSize":"20px",
            "fontWeight":"200",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":155,
              "y":92},
            "size":{
              "width":220,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8bf04baeb54465f9160c2c4822f440f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSansLight', 'Fira Sans Light', 'Fira Sans'",
                "fontSize":"20px",
                "fontWeight":"200",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":155,
                  "y":92},
                "size":{
                  "width":220,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc132b0a73d54b0587c02d89f77ee0fe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":75},
            "size":{
              "width":64,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"989760564cec4e25b23c1032b36f81b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":75},
                "size":{
                  "width":64,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u20.png"}},
{
          "id":"671966677935458fa98da54da8ab4b8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":220},
            "size":{
              "width":610,
              "height":65},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f54c3e67d2e409d81361c526d4552aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":220},
                "size":{
                  "width":610,
                  "height":65},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/10a_edit__manifest__version___publishing/u6.png"}},
{
          "id":"eaadd83b76b54d678b6961faae966974",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSansLight', 'Fira Sans Light', 'Fira Sans'",
            "fontSize":"20px",
            "fontWeight":"200",
            "location":{
              "x":330,
              "y":180},
            "size":{
              "width":141,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e598cdbc6d0849a9b3f983ca68727789",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSansLight', 'Fira Sans Light', 'Fira Sans'",
                "fontSize":"20px",
                "fontWeight":"200",
                "location":{
                  "x":330,
                  "y":180},
                "size":{
                  "width":141,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3307a067b2db49c3a535d6e62fc36697",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":80,
              "y":30},
            "size":{
              "width":431,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1dcd72daa744b3eb5a132b385abe856",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":80,
                  "y":30},
                "size":{
                  "width":431,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 9 my submissions in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"9_my_submissions.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3d6bb0ecdc540fbbb877791d6180a98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "location":{
              "x":80,
              "y":170},
            "size":{
              "width":220,
              "height":280},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "linePattern":"none",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce9d8542b0744649861c33ab4d35e5d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "location":{
                  "x":80,
                  "y":170},
                "size":{
                  "width":220,
                  "height":280},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "linePattern":"none",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/10a_edit__manifest__version___publishing/u12.png"}},
{
          "id":"5e73b89113cc480dbb6f9597761bd310",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":170},
            "size":{
              "width":220,
              "height":40},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "linePattern":"none",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eec941d1ddfc405ab3cefe5773ed3396",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":170},
                "size":{
                  "width":220,
                  "height":40},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "linePattern":"none",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_upload_manifest/u8.png"}},
{
          "id":"1de52cfa8b4243bf943809ab09da6f9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":220},
            "size":{
              "width":122,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19a9bb08ca424f4ea8ee47ae58d45db6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":220},
                "size":{
                  "width":122,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 11 edit, general information in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"11_edit__general_information.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99e7ac27df134bb4807c56064739dabf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":260},
            "size":{
              "width":64,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cf3f623dd004683953f09c273c9f731",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":260},
                "size":{
                  "width":64,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 12 edit, categories in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"12_edit__categories.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2bf5d4128a54cfb85de33bd1456586d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":300},
            "size":{
              "width":133,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63c972083be1436a8f359d002868b55d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":300},
                "size":{
                  "width":133,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26be3958c09a4e38937bfea70bf21a57",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":340},
            "size":{
              "width":91,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"764f3932bf6048b4a5ac41436207abf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":340},
                "size":{
                  "width":91,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80e2644f33bd4c4da9a31cf64dfa4718",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":420},
            "size":{
              "width":128,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6791da633140468389c4b09ea9c80870",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":420},
                "size":{
                  "width":128,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86cd55952319478ea4ed2afc2868fccd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":380},
            "size":{
              "width":46,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b20789f325e945e9ba3ee3cbb198afb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":380},
                "size":{
                  "width":46,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca8be23efd154adc9911fe5a3b650ced",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":180},
            "size":{
              "width":183,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"090c0d52c6214279a1f17b19af78a773",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":180},
                "size":{
                  "width":183,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8038c128cf642fc952efd5fe886d8f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":360},
            "size":{
              "width":610,
              "height":65},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4601bfcee19c439799a6a3c916eeb193",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":360},
                "size":{
                  "width":610,
                  "height":65},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/10a_edit__manifest__version___publishing/u6.png"}},
{
          "id":"978f92d08fc0443eaa04f4bb00f24918",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSansLight', 'Fira Sans Light', 'Fira Sans'",
            "fontSize":"20px",
            "fontWeight":"200",
            "location":{
              "x":330,
              "y":320},
            "size":{
              "width":45,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1150f0477d68476db87a972f7672212f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSansLight', 'Fira Sans Light', 'Fira Sans'",
                "fontSize":"20px",
                "fontWeight":"200",
                "location":{
                  "x":330,
                  "y":320},
                "size":{
                  "width":45,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"869c3ce4c184438e80c9d8c1f7905811",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":500},
            "size":{
              "width":610,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57fdc5f4d25c437596e6852966ee0b6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":500},
                "size":{
                  "width":610,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/10b_submitted/u34.png"}},
{
          "id":"f337d5b041d046efa377678b1c4f4b9f",
          "label":"1.1.4",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":321,
              "y":545},
            "size":{
              "width":608,
              "height":390}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"bdc46cafaf5c49118a6a3a7933983a2a",
              "label":"minimized",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"eb6d32e3a07b4d9e91072866632453cb",
                  "label":"",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFFCC}}},
                    "size":{
                      "width":608,
                      "height":75},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"10"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cdd7c6e8113646c8bfdc5d14abc64ffc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFFCC}}},
                        "size":{
                          "width":608,
                          "height":75},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"10"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set 1.1.4 to maximized",
                              "panelsToStates":[{
                                  "panelPath":["f337d5b041d046efa377678b1c4f4b9f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/10b_submitted/u37.png",
                    "mouseOver~":"images/10b_submitted/u37_mouseOver.png"}},
{
                  "id":"3b2641a02fc243a6bdfd19fc91c22c11",
                  "label":"",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":49,
                      "y":10},
                    "size":{
                      "width":32,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9a68317ae9e7486ab6e2d212db3568e1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":49,
                          "y":10},
                        "size":{
                          "width":32,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/2a_screenshot/u20.png"}},
{
                  "id":"102c2fd184d04d678dd4fe094a2c94c6",
                  "label":"name text",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "fontSize":"15px",
                    "fontWeight":"400",
                    "stateStyles":{
                      "mouseOver":{
}},
                    "location":{
                      "x":99,
                      "y":15},
                    "size":{
                      "width":29,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"72372370fb2f4a9ca402251b75bc65a3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans', 'Fira Sans'",
                        "fontSize":"15px",
                        "fontWeight":"400",
                        "stateStyles":{
                          "mouseOver":{
}},
                        "location":{
                          "x":99,
                          "y":15},
                        "size":{
                          "width":29,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6733c86a587c4163bff0ef1afd4c9c89",
                  "label":"",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000},
                    "location":{
                      "x":24,
                      "y":22},
                    "size":{
                      "width":9,
                      "height":9},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bbffa2b05a564b39b022a1e3655b6764",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF000000},
                        "location":{
                          "x":24,
                          "y":22},
                        "size":{
                          "width":9,
                          "height":9},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/10a_edit__manifest__version___publishing/u42.png"}},
{
                  "id":"2b272327eca849319583f8e45da880d9",
                  "label":"name text",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "fontSize":"15px",
                    "fontWeight":"400",
                    "stateStyles":{
                      "mouseOver":{
}},
                    "location":{
                      "x":359,
                      "y":15},
                    "size":{
                      "width":42,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4c3f968493594245a6b0af93fd118420",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans', 'Fira Sans'",
                        "fontSize":"15px",
                        "fontWeight":"400",
                        "stateStyles":{
                          "mouseOver":{
}},
                        "location":{
                          "x":359,
                          "y":15},
                        "size":{
                          "width":42,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"488312c264c14983aea1b5a4ab1e8cca",
                  "label":"name text",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "fontSize":"15px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
}},
                    "location":{
                      "x":189,
                      "y":15},
                    "size":{
                      "width":105,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0ef17236185d4eeb94bbd84596c52c1a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans', 'Fira Sans'",
                        "fontSize":"15px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
}},
                        "location":{
                          "x":189,
                          "y":15},
                        "size":{
                          "width":105,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"60b5aad4631647ff933dc2e15ccdcdd1",
                  "label":"name text",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "fontSize":"12px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
}},
                    "location":{
                      "x":189,
                      "y":35},
                    "size":{
                      "width":133,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6d4142db81bb4fbd8efba98a1635943c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans', 'Fira Sans'",
                        "fontSize":"12px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
}},
                        "location":{
                          "x":189,
                          "y":35},
                        "size":{
                          "width":133,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open 10b rejected in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"10b_rejected.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"006de33694c3497db8ba77f5275df208",
              "label":"maximized",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c27d52f54088457ab6fe44e007f955cb",
                  "label":"",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFFCC}}},
                    "size":{
                      "width":608,
                      "height":390},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"10"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"878f0ac5506741cdb165869956f239d5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFFCC}}},
                        "size":{
                          "width":608,
                          "height":390},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"10"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set 1.1.4 to minimized",
                              "panelsToStates":[{
                                  "panelPath":["f337d5b041d046efa377678b1c4f4b9f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/10b_submitted/u51.png",
                    "mouseOver~":"images/10b_submitted/u51_mouseOver.png"}},
{
                  "id":"8baec644b7a049be8e0bb2c34e8e1ae1",
                  "label":"",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":49,
                      "y":10},
                    "size":{
                      "width":32,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"79c0968310554287b1b4ac17f94750d3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":49,
                          "y":10},
                        "size":{
                          "width":32,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/2a_screenshot/u20.png"}},
{
                  "id":"ae2c3dd4cf2a4541a59862b2b760503d",
                  "label":"name text",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "fontSize":"15px",
                    "fontWeight":"400",
                    "stateStyles":{
                      "mouseOver":{
}},
                    "location":{
                      "x":99,
                      "y":15},
                    "size":{
                      "width":29,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"67772a86f12047d5b99dbad6638d4a8f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans', 'Fira Sans'",
                        "fontSize":"15px",
                        "fontWeight":"400",
                        "stateStyles":{
                          "mouseOver":{
}},
                        "location":{
                          "x":99,
                          "y":15},
                        "size":{
                          "width":29,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"85822a32bad04a17a85d568eefd5d72b",
                  "label":"",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000},
                    "location":{
                      "x":24,
                      "y":22},
                    "size":{
                      "width":9,
                      "height":9},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"040e5915e4444bb888ea4512913afc94",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF000000},
                        "location":{
                          "x":24,
                          "y":22},
                        "size":{
                          "width":9,
                          "height":9},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/10b_submitted/u57.png"}},
{
                  "id":"0cd30e74a3a148f1961041823ef07733",
                  "label":"name text",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "fontSize":"15px",
                    "fontWeight":"400",
                    "stateStyles":{
                      "mouseOver":{
}},
                    "location":{
                      "x":359,
                      "y":15},
                    "size":{
                      "width":42,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"536ace9e1e2c49aa846031795c7b2fb2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans', 'Fira Sans'",
                        "fontSize":"15px",
                        "fontWeight":"400",
                        "stateStyles":{
                          "mouseOver":{
}},
                        "location":{
                          "x":359,
                          "y":15},
                        "size":{
                          "width":42,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"42630aaec235498a838ad3e423bf2201",
                  "label":"name text",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "fontSize":"15px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
}},
                    "location":{
                      "x":189,
                      "y":15},
                    "size":{
                      "width":105,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bc3e1449c64b4e109b951b627a0b15f4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans', 'Fira Sans'",
                        "fontSize":"15px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
}},
                        "location":{
                          "x":189,
                          "y":15},
                        "size":{
                          "width":105,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e59b076b23ba4a279dfdc203719290df",
                  "label":"",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF1F1F1},
                    "location":{
                      "x":19,
                      "y":50},
                    "size":{
                      "width":570,
                      "height":315},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "linePattern":"none",
                    "cornerRadiusTopLeft":"10"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7b669e14fa4b4f81b5f0ea8ab4353ba0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF1F1F1},
                        "location":{
                          "x":19,
                          "y":50},
                        "size":{
                          "width":570,
                          "height":315},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "linePattern":"none",
                        "cornerRadiusTopLeft":"10"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/10b_submitted/u63.png"}},
{
                  "id":"03e6a0d7a21242bd96a08699a3dcdbb9",
                  "label":"",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":19,
                      "y":165},
                    "size":{
                      "width":220,
                      "height":40},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "linePattern":"none"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2bd80a266e6c4473a7315852f4b610fc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":19,
                          "y":165},
                        "size":{
                          "width":220,
                          "height":40},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "linePattern":"none"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/2a_screenshot/u122.png"}},
{
                  "id":"908e118f579a49849835bf6da89fc55e",
                  "label":"",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "location":{
                      "x":34,
                      "y":175},
                    "size":{
                      "width":45,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a5c3c21e4a094a68b6574eebb6e83e06",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans', 'Fira Sans'",
                        "location":{
                          "x":34,
                          "y":175},
                        "size":{
                          "width":45,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9f4250bd03884bb89a4e4af6e43a3976",
                  "label":"",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "fontSize":"11px",
                    "horizontalAlignment":"right",
                    "location":{
                      "x":187,
                      "y":177},
                    "size":{
                      "width":37,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6040705d0d2549498427aac222faf409",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans', 'Fira Sans'",
                        "fontSize":"11px",
                        "horizontalAlignment":"right",
                        "location":{
                          "x":187,
                          "y":177},
                        "size":{
                          "width":37,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"68c4c1d07e584b6c9a4ebf3f25f667d4",
                  "label":"",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSansMedium', 'Fira Sans Medium', 'Fira Sans'",
                    "fontSize":"15px",
                    "fontWeight":"500",
                    "location":{
                      "x":34,
                      "y":130},
                    "size":{
                      "width":74,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a2e7cf1003534e938030e5dc5595225f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSansMedium', 'Fira Sans Medium', 'Fira Sans'",
                        "fontSize":"15px",
                        "fontWeight":"500",
                        "location":{
                          "x":34,
                          "y":130},
                        "size":{
                          "width":74,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9c69594c030c40bcb45ce14a406ee07e",
                  "label":"",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":34,
                      "y":215},
                    "size":{
                      "width":103,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1f4e32ff48354b0691f067389d8c1adc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans', 'Fira Sans'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "location":{
                          "x":34,
                          "y":215},
                        "size":{
                          "width":103,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fe6850e862c549a5a7c136f027f624bc",
                  "label":"",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans-Bold', 'Fira Sans Bold', 'Fira Sans'",
                    "fontWeight":"700",
                    "location":{
                      "x":261,
                      "y":132},
                    "size":{
                      "width":85,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c6efae904d134365bcaddd8427c1cf06",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans-Bold', 'Fira Sans Bold', 'Fira Sans'",
                        "fontWeight":"700",
                        "location":{
                          "x":261,
                          "y":132},
                        "size":{
                          "width":85,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7e3613338fb54a559900012ce2460d9c",
                  "label":"",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":1,
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":234,
                      "y":115},
                    "size":{
                      "width":10,
                      "height":250},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/10b_submitted/u77_line.png"}},
{
                  "id":"8efbac3e3f2e4a83a192ee9b927dfc49",
                  "label":"",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":1,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":19,
                      "y":110},
                    "size":{
                      "width":570,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/10b_submitted/u78_line.png"}},
{
                  "id":"6cd42625745b4b06a61380979f25dbc0",
                  "label":"",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans-Bold', 'Fira Sans Bold', 'Fira Sans'",
                    "fontWeight":"700",
                    "location":{
                      "x":34,
                      "y":72},
                    "size":{
                      "width":80,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"da649b4b368e4c55aa716affce8febe1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans-Bold', 'Fira Sans Bold', 'Fira Sans'",
                        "fontWeight":"700",
                        "location":{
                          "x":34,
                          "y":72},
                        "size":{
                          "width":80,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bee6047cbbd349fa94ba8864a0cfb71f",
                  "label":"",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":1,
                  "type":"textArea",
                  "styleType":"textArea",
                  "disabled":true,
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "fontSize":"12px",
                    "location":{
                      "x":259,
                      "y":160},
                    "size":{
                      "width":300,
                      "height":180}},
                  "adaptiveStyles":{
}},
{
                  "id":"4a6fe011a79d48fb954d288da0121e14",
                  "label":"",
                  "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "location":{
                      "x":129,
                      "y":72},
                    "size":{
                      "width":261,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3d2a99795b084ce3bdd3f4ca652a896f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f337d5b041d046efa377678b1c4f4b9f",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans', 'Fira Sans'",
                        "location":{
                          "x":129,
                          "y":72},
                        "size":{
                          "width":261,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"d91fa672305147bdb750500bda90cbd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSansLight', 'Fira Sans Light', 'Fira Sans'",
            "fontSize":"20px",
            "fontWeight":"200",
            "location":{
              "x":330,
              "y":460},
            "size":{
              "width":94,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6331b627271b4051bce4e19f020eab48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSansLight', 'Fira Sans Light', 'Fira Sans'",
                "fontSize":"20px",
                "fontWeight":"200",
                "location":{
                  "x":330,
                  "y":460},
                "size":{
                  "width":94,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1465cb5ac8364058bff13a285243100a",
          "label":"name text",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "fontWeight":"400",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":340,
              "y":240},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d5ba5cab01d471bb0bf3eff0265b474",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "fontWeight":"400",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":340,
                  "y":240},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e10c52da84ee4f02975bfae4d49ec705",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF4CB1FF},
{
                  "color":0xFF4CB1FF},
{
                  "color":0xFF1793E5},
{
                  "color":0xFF1793E5}]},
            "location":{
              "x":710,
              "y":314},
            "size":{
              "width":220,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF1793E5},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e5352677675478fbd77b3e7c8b8efee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF4CB1FF},
{
                      "color":0xFF4CB1FF},
{
                      "color":0xFF1793E5},
{
                      "color":0xFF1793E5}]},
                "location":{
                  "x":710,
                  "y":314},
                "size":{
                  "width":220,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF1793E5},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_my_submissions/u2.png"}},
{
          "id":"8ba0227b15d744b79226af7145a59331",
          "label":"name text",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'FiraSans-Bold', 'Fira Sans Bold', 'Fira Sans'",
            "fontSize":"15px",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":420,
              "y":520},
            "size":{
              "width":53,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d4121364f344d7eaaf008a9f29c4627",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans-Bold', 'Fira Sans Bold', 'Fira Sans'",
                "fontSize":"15px",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":420,
                  "y":520},
                "size":{
                  "width":53,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"426f4134ec734721a66a2d1441484ed2",
          "label":"name text",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'FiraSans-Bold', 'Fira Sans Bold', 'Fira Sans'",
            "fontSize":"15px",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":680,
              "y":520},
            "size":{
              "width":67,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb5aa3cf1e7f40ab9ffc60bf16acade3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans-Bold', 'Fira Sans Bold', 'Fira Sans'",
                "fontSize":"15px",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":680,
                  "y":520},
                "size":{
                  "width":67,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"206d11a4e4c849ecb650052ff6c3969f",
          "label":"name text",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "fontWeight":"400",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":340,
              "y":380},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86d98814f90b4ab392db57c0a114d5c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "fontWeight":"400",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":340,
                  "y":380},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"baee8ec0f8b140e6893d23f6b52bd8d3",
          "label":"name text",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'FiraSans-Bold', 'Fira Sans Bold', 'Fira Sans'",
            "fontSize":"15px",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":510,
              "y":520},
            "size":{
              "width":46,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2b8e50b7e9e481fabdc2049d87bd132",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans-Bold', 'Fira Sans Bold', 'Fira Sans'",
                "fontSize":"15px",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":510,
                  "y":520},
                "size":{
                  "width":46,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "068958af0f4a497a9237fab6b8a2abc0":{
      "scriptId":"u0"},
    "afbd9078f47e46038c0a9b30d33e2b96":{
      "scriptId":"u1"},
    "759bf3ea56384964b1eadf82c37a5d38":{
      "scriptId":"u2"},
    "c8bf04baeb54465f9160c2c4822f440f":{
      "scriptId":"u3"},
    "cc132b0a73d54b0587c02d89f77ee0fe":{
      "scriptId":"u4"},
    "989760564cec4e25b23c1032b36f81b1":{
      "scriptId":"u5"},
    "671966677935458fa98da54da8ab4b8e":{
      "scriptId":"u6"},
    "3f54c3e67d2e409d81361c526d4552aa":{
      "scriptId":"u7"},
    "eaadd83b76b54d678b6961faae966974":{
      "scriptId":"u8"},
    "e598cdbc6d0849a9b3f983ca68727789":{
      "scriptId":"u9"},
    "3307a067b2db49c3a535d6e62fc36697":{
      "scriptId":"u10"},
    "f1dcd72daa744b3eb5a132b385abe856":{
      "scriptId":"u11"},
    "f3d6bb0ecdc540fbbb877791d6180a98":{
      "scriptId":"u12"},
    "ce9d8542b0744649861c33ab4d35e5d8":{
      "scriptId":"u13"},
    "5e73b89113cc480dbb6f9597761bd310":{
      "scriptId":"u14"},
    "eec941d1ddfc405ab3cefe5773ed3396":{
      "scriptId":"u15"},
    "1de52cfa8b4243bf943809ab09da6f9f":{
      "scriptId":"u16"},
    "19a9bb08ca424f4ea8ee47ae58d45db6":{
      "scriptId":"u17"},
    "99e7ac27df134bb4807c56064739dabf":{
      "scriptId":"u18"},
    "6cf3f623dd004683953f09c273c9f731":{
      "scriptId":"u19"},
    "f2bf5d4128a54cfb85de33bd1456586d":{
      "scriptId":"u20"},
    "63c972083be1436a8f359d002868b55d":{
      "scriptId":"u21"},
    "26be3958c09a4e38937bfea70bf21a57":{
      "scriptId":"u22"},
    "764f3932bf6048b4a5ac41436207abf1":{
      "scriptId":"u23"},
    "80e2644f33bd4c4da9a31cf64dfa4718":{
      "scriptId":"u24"},
    "6791da633140468389c4b09ea9c80870":{
      "scriptId":"u25"},
    "86cd55952319478ea4ed2afc2868fccd":{
      "scriptId":"u26"},
    "b20789f325e945e9ba3ee3cbb198afb4":{
      "scriptId":"u27"},
    "ca8be23efd154adc9911fe5a3b650ced":{
      "scriptId":"u28"},
    "090c0d52c6214279a1f17b19af78a773":{
      "scriptId":"u29"},
    "e8038c128cf642fc952efd5fe886d8f5":{
      "scriptId":"u30"},
    "4601bfcee19c439799a6a3c916eeb193":{
      "scriptId":"u31"},
    "978f92d08fc0443eaa04f4bb00f24918":{
      "scriptId":"u32"},
    "1150f0477d68476db87a972f7672212f":{
      "scriptId":"u33"},
    "869c3ce4c184438e80c9d8c1f7905811":{
      "scriptId":"u34"},
    "57fdc5f4d25c437596e6852966ee0b6b":{
      "scriptId":"u35"},
    "f337d5b041d046efa377678b1c4f4b9f":{
      "scriptId":"u36"},
    "eb6d32e3a07b4d9e91072866632453cb":{
      "scriptId":"u37"},
    "cdd7c6e8113646c8bfdc5d14abc64ffc":{
      "scriptId":"u38"},
    "3b2641a02fc243a6bdfd19fc91c22c11":{
      "scriptId":"u39"},
    "9a68317ae9e7486ab6e2d212db3568e1":{
      "scriptId":"u40"},
    "102c2fd184d04d678dd4fe094a2c94c6":{
      "scriptId":"u41"},
    "72372370fb2f4a9ca402251b75bc65a3":{
      "scriptId":"u42"},
    "6733c86a587c4163bff0ef1afd4c9c89":{
      "scriptId":"u43"},
    "bbffa2b05a564b39b022a1e3655b6764":{
      "scriptId":"u44"},
    "2b272327eca849319583f8e45da880d9":{
      "scriptId":"u45"},
    "4c3f968493594245a6b0af93fd118420":{
      "scriptId":"u46"},
    "488312c264c14983aea1b5a4ab1e8cca":{
      "scriptId":"u47"},
    "0ef17236185d4eeb94bbd84596c52c1a":{
      "scriptId":"u48"},
    "60b5aad4631647ff933dc2e15ccdcdd1":{
      "scriptId":"u49"},
    "6d4142db81bb4fbd8efba98a1635943c":{
      "scriptId":"u50"},
    "c27d52f54088457ab6fe44e007f955cb":{
      "scriptId":"u51"},
    "878f0ac5506741cdb165869956f239d5":{
      "scriptId":"u52"},
    "8baec644b7a049be8e0bb2c34e8e1ae1":{
      "scriptId":"u53"},
    "79c0968310554287b1b4ac17f94750d3":{
      "scriptId":"u54"},
    "ae2c3dd4cf2a4541a59862b2b760503d":{
      "scriptId":"u55"},
    "67772a86f12047d5b99dbad6638d4a8f":{
      "scriptId":"u56"},
    "85822a32bad04a17a85d568eefd5d72b":{
      "scriptId":"u57"},
    "040e5915e4444bb888ea4512913afc94":{
      "scriptId":"u58"},
    "0cd30e74a3a148f1961041823ef07733":{
      "scriptId":"u59"},
    "536ace9e1e2c49aa846031795c7b2fb2":{
      "scriptId":"u60"},
    "42630aaec235498a838ad3e423bf2201":{
      "scriptId":"u61"},
    "bc3e1449c64b4e109b951b627a0b15f4":{
      "scriptId":"u62"},
    "e59b076b23ba4a279dfdc203719290df":{
      "scriptId":"u63"},
    "7b669e14fa4b4f81b5f0ea8ab4353ba0":{
      "scriptId":"u64"},
    "03e6a0d7a21242bd96a08699a3dcdbb9":{
      "scriptId":"u65"},
    "2bd80a266e6c4473a7315852f4b610fc":{
      "scriptId":"u66"},
    "908e118f579a49849835bf6da89fc55e":{
      "scriptId":"u67"},
    "a5c3c21e4a094a68b6574eebb6e83e06":{
      "scriptId":"u68"},
    "9f4250bd03884bb89a4e4af6e43a3976":{
      "scriptId":"u69"},
    "6040705d0d2549498427aac222faf409":{
      "scriptId":"u70"},
    "68c4c1d07e584b6c9a4ebf3f25f667d4":{
      "scriptId":"u71"},
    "a2e7cf1003534e938030e5dc5595225f":{
      "scriptId":"u72"},
    "9c69594c030c40bcb45ce14a406ee07e":{
      "scriptId":"u73"},
    "1f4e32ff48354b0691f067389d8c1adc":{
      "scriptId":"u74"},
    "fe6850e862c549a5a7c136f027f624bc":{
      "scriptId":"u75"},
    "c6efae904d134365bcaddd8427c1cf06":{
      "scriptId":"u76"},
    "7e3613338fb54a559900012ce2460d9c":{
      "scriptId":"u77"},
    "8efbac3e3f2e4a83a192ee9b927dfc49":{
      "scriptId":"u78"},
    "6cd42625745b4b06a61380979f25dbc0":{
      "scriptId":"u79"},
    "da649b4b368e4c55aa716affce8febe1":{
      "scriptId":"u80"},
    "bee6047cbbd349fa94ba8864a0cfb71f":{
      "scriptId":"u81"},
    "4a6fe011a79d48fb954d288da0121e14":{
      "scriptId":"u82"},
    "3d2a99795b084ce3bdd3f4ca652a896f":{
      "scriptId":"u83"},
    "d91fa672305147bdb750500bda90cbd0":{
      "scriptId":"u84"},
    "6331b627271b4051bce4e19f020eab48":{
      "scriptId":"u85"},
    "1465cb5ac8364058bff13a285243100a":{
      "scriptId":"u86"},
    "4d5ba5cab01d471bb0bf3eff0265b474":{
      "scriptId":"u87"},
    "e10c52da84ee4f02975bfae4d49ec705":{
      "scriptId":"u88"},
    "4e5352677675478fbd77b3e7c8b8efee":{
      "scriptId":"u89"},
    "8ba0227b15d744b79226af7145a59331":{
      "scriptId":"u90"},
    "8d4121364f344d7eaaf008a9f29c4627":{
      "scriptId":"u91"},
    "426f4134ec734721a66a2d1441484ed2":{
      "scriptId":"u92"},
    "bb5aa3cf1e7f40ab9ffc60bf16acade3":{
      "scriptId":"u93"},
    "206d11a4e4c849ecb650052ff6c3969f":{
      "scriptId":"u94"},
    "86d98814f90b4ab392db57c0a114d5c0":{
      "scriptId":"u95"},
    "baee8ec0f8b140e6893d23f6b52bd8d3":{
      "scriptId":"u96"},
    "f2b8e50b7e9e481fabdc2049d87bd132":{
      "scriptId":"u97"}}});