$axure.loadCurrentPage({
  "url":"1_upload_manifest.html",
  "generationDate":new Date(1399363401571.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"name"],
  "page":{
    "packageId":"25bd093181a34edbad9fce1baf11e27f",
    "type":"Axure:Page",
    "name":"1 upload manifest",
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"068958af0f4a497a9237fab6b8a2abc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE7E7E7},
            "size":{
              "width":2400,
              "height":2400},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afbd9078f47e46038c0a9b30d33e2b96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE7E7E7},
                "size":{
                  "width":2400,
                  "height":2400},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_my_submissions/u0.png"}},
{
          "id":"18d7cb9d6cff4966a8a60866259d0980",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF4CB1FF},
{
                  "color":0xFF4CB1FF},
{
                  "color":0xFF1793E5},
{
                  "color":0xFF1793E5}]},
            "location":{
              "x":320,
              "y":127},
            "size":{
              "width":160,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF1793E5},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5088e8497ab486897a59d6d09b2eaee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF4CB1FF},
{
                      "color":0xFF4CB1FF},
{
                      "color":0xFF1793E5},
{
                      "color":0xFF1793E5}]},
                "location":{
                  "x":320,
                  "y":127},
                "size":{
                  "width":160,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF1793E5},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 2a screenshot in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"2a_screenshot.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/1_upload_manifest/u2.png"}},
{
          "id":"a384481cee8448f4965a00f1dc61858d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":320,
              "y":80},
            "size":{
              "width":180,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"accaaf69968342cc832c78452b302d48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":320,
                  "y":80},
                "size":{
                  "width":180,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33a6c7c1283243b096df18b8ae3119fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "location":{
              "x":80,
              "y":80},
            "size":{
              "width":220,
              "height":320},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "linePattern":"none",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0818282921945788f54fab31b4a659d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "location":{
                  "x":80,
                  "y":80},
                "size":{
                  "width":220,
                  "height":320},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "linePattern":"none",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_upload_manifest/u6.png"}},
{
          "id":"1abf5072c4714f57930967615f1fdb31",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":80},
            "size":{
              "width":220,
              "height":40},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "linePattern":"none",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c7b3a441e9641daa0abd0baef422f80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":80},
                "size":{
                  "width":220,
                  "height":40},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "linePattern":"none",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_upload_manifest/u8.png"}},
{
          "id":"3730b92b0e56400581487d887c5f00aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":90},
            "size":{
              "width":52,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31206d6619024a48b98080278d54235a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":90},
                "size":{
                  "width":52,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"afb8923dffb44094baf8ac1d615d6489",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":130},
            "size":{
              "width":122,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5905d504290647898c94f5075c6cff01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":130},
                "size":{
                  "width":122,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6cc245d4bf140e29aed5ca67098b2b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":170},
            "size":{
              "width":64,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9763793e901b409db82a5b468c07c1a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":170},
                "size":{
                  "width":64,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38966b0419de4e278e4c8629ebba50c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":210},
            "size":{
              "width":133,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"653567209d054d8ca81f89e89c026b24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":210},
                "size":{
                  "width":133,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b469e0abf92440d598a4413fc163cae4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":250},
            "size":{
              "width":91,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c78ef006f24f4e2998b121413a543405",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":250},
                "size":{
                  "width":91,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5d62b495ecd4aedb6f3b164fccf7254",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":330},
            "size":{
              "width":128,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b39c082b49a74274982d86274a8af78d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":330},
                "size":{
                  "width":128,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06e3b57968464b71aa9e6a16d8f26654",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":370},
            "size":{
              "width":80,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aba4a2f8f1dc4faf9b0df6b9dc40264c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":370},
                "size":{
                  "width":80,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e4c60a7e4e54eb48d419a7128daf8b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":290},
            "size":{
              "width":46,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"294383f4afeb4437aec4dc77e8c590dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":290},
                "size":{
                  "width":46,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc33139e383e40c8aab50f84e79cdaec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":80,
              "y":30},
            "size":{
              "width":232,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99b8a9f8266441b880d46d062f61258b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":80,
                  "y":30},
                "size":{
                  "width":232,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 9 my submissions in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"9_my_submissions.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "068958af0f4a497a9237fab6b8a2abc0":{
      "scriptId":"u0"},
    "afbd9078f47e46038c0a9b30d33e2b96":{
      "scriptId":"u1"},
    "18d7cb9d6cff4966a8a60866259d0980":{
      "scriptId":"u2"},
    "d5088e8497ab486897a59d6d09b2eaee":{
      "scriptId":"u3"},
    "a384481cee8448f4965a00f1dc61858d":{
      "scriptId":"u4"},
    "accaaf69968342cc832c78452b302d48":{
      "scriptId":"u5"},
    "33a6c7c1283243b096df18b8ae3119fd":{
      "scriptId":"u6"},
    "e0818282921945788f54fab31b4a659d":{
      "scriptId":"u7"},
    "1abf5072c4714f57930967615f1fdb31":{
      "scriptId":"u8"},
    "7c7b3a441e9641daa0abd0baef422f80":{
      "scriptId":"u9"},
    "3730b92b0e56400581487d887c5f00aa":{
      "scriptId":"u10"},
    "31206d6619024a48b98080278d54235a":{
      "scriptId":"u11"},
    "afb8923dffb44094baf8ac1d615d6489":{
      "scriptId":"u12"},
    "5905d504290647898c94f5075c6cff01":{
      "scriptId":"u13"},
    "d6cc245d4bf140e29aed5ca67098b2b5":{
      "scriptId":"u14"},
    "9763793e901b409db82a5b468c07c1a5":{
      "scriptId":"u15"},
    "38966b0419de4e278e4c8629ebba50c2":{
      "scriptId":"u16"},
    "653567209d054d8ca81f89e89c026b24":{
      "scriptId":"u17"},
    "b469e0abf92440d598a4413fc163cae4":{
      "scriptId":"u18"},
    "c78ef006f24f4e2998b121413a543405":{
      "scriptId":"u19"},
    "f5d62b495ecd4aedb6f3b164fccf7254":{
      "scriptId":"u20"},
    "b39c082b49a74274982d86274a8af78d":{
      "scriptId":"u21"},
    "06e3b57968464b71aa9e6a16d8f26654":{
      "scriptId":"u22"},
    "aba4a2f8f1dc4faf9b0df6b9dc40264c":{
      "scriptId":"u23"},
    "7e4c60a7e4e54eb48d419a7128daf8b6":{
      "scriptId":"u24"},
    "294383f4afeb4437aec4dc77e8c590dd":{
      "scriptId":"u25"},
    "cc33139e383e40c8aab50f84e79cdaec":{
      "scriptId":"u26"},
    "99b8a9f8266441b880d46d062f61258b":{
      "scriptId":"u27"}}});