$axure.loadCurrentPage({
  "url":"0_my_submissions.html",
  "generationDate":new Date(1399021337011.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"name"],
  "page":{
    "packageId":"f199121beb444e99a6a4ac86329fcf21",
    "type":"Axure:Page",
    "name":"0 my submissions",
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"068958af0f4a497a9237fab6b8a2abc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE7E7E7},
            "size":{
              "width":2400,
              "height":2400},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afbd9078f47e46038c0a9b30d33e2b96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE7E7E7},
                "size":{
                  "width":2400,
                  "height":2400},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_my_submissions/u0.png"}},
{
          "id":"ea859d01bd3543908c48cf5c2aef1854",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF4CB1FF},
{
                  "color":0xFF4CB1FF},
{
                  "color":0xFF1793E5},
{
                  "color":0xFF1793E5}]},
            "location":{
              "x":780,
              "y":34},
            "size":{
              "width":220,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF1793E5},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1ee20bdaf3741fa8b0cbcbfd5cdf7cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF4CB1FF},
{
                      "color":0xFF4CB1FF},
{
                      "color":0xFF1793E5},
{
                      "color":0xFF1793E5}]},
                "location":{
                  "x":780,
                  "y":34},
                "size":{
                  "width":220,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF1793E5},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 1 upload manifest in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"1_upload_manifest.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_my_submissions/u2.png"}},
{
          "id":"f97849258d944410b715a13cca323c2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSansLight', 'Fira Sans Light', 'Fira Sans'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":90,
              "y":40},
            "size":{
              "width":129,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaf656ff96094387bf09dc15f54e4106",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSansLight', 'Fira Sans Light', 'Fira Sans'",
                "fontSize":"18px",
                "fontWeight":"200",
                "location":{
                  "x":90,
                  "y":40},
                "size":{
                  "width":129,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "068958af0f4a497a9237fab6b8a2abc0":{
      "scriptId":"u0"},
    "afbd9078f47e46038c0a9b30d33e2b96":{
      "scriptId":"u1"},
    "ea859d01bd3543908c48cf5c2aef1854":{
      "scriptId":"u2"},
    "d1ee20bdaf3741fa8b0cbcbfd5cdf7cb":{
      "scriptId":"u3"},
    "f97849258d944410b715a13cca323c2f":{
      "scriptId":"u4"},
    "aaf656ff96094387bf09dc15f54e4106":{
      "scriptId":"u5"}}});