$axure.loadCurrentPage({
  "url":"2b_description.html",
  "generationDate":new Date(1399021339078.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"name"],
  "page":{
    "packageId":"436abcfeacf045bea503eabbbda8eeb3",
    "type":"Axure:Page",
    "name":"2b description",
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"068958af0f4a497a9237fab6b8a2abc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE7E7E7},
            "size":{
              "width":2400,
              "height":2400},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afbd9078f47e46038c0a9b30d33e2b96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE7E7E7},
                "size":{
                  "width":2400,
                  "height":2400},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_my_submissions/u0.png"}},
{
          "id":"240845c1c5ec497bae383ef3ca257183",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":80},
            "size":{
              "width":320,
              "height":1145},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cbf4b1302d54c30b9f1336c1a79b264",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":80},
                "size":{
                  "width":320,
                  "height":1145},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u2.png"}},
{
          "id":"f32859cf52494a8baf0d2ed7a42c16ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA7A7A7,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":650,
              "y":122},
            "size":{
              "width":54,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f8eb2c37a31462589c5fc390bd404ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA7A7A7,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":650,
                  "y":122},
                "size":{
                  "width":54,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b144a4fb0ac14ff39f2c83ece7200767",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA7A7A7,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":650,
              "y":137},
            "size":{
              "width":63,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e622920565d84ae2ab6da890378ed0e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA7A7A7,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":650,
                  "y":137},
                "size":{
                  "width":63,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d9c6a2021bd4bc4baabfb914bf7645e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "location":{
              "x":560,
              "y":175},
            "size":{
              "width":320,
              "height":230},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4fb28d747db4018a896bc301899d246",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "location":{
                  "x":560,
                  "y":175},
                "size":{
                  "width":320,
                  "height":230},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u8.png"}},
{
          "id":"255d878e864a4762b2f564aa723c2871",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":175},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b139eafafc534e4582ef8580adcbfac0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":175},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u10.png"}},
{
          "id":"8580e2a4213549eb83500888a1d2c7dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSansMedium', 'Fira Sans Medium', 'Fira Sans'",
            "fontSize":"15px",
            "fontWeight":"500",
            "location":{
              "x":570,
              "y":420},
            "size":{
              "width":300,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67e8d18e30f14b09b2812b29914bc7ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSansMedium', 'Fira Sans Medium', 'Fira Sans'",
                "fontSize":"15px",
                "fontWeight":"500",
                "location":{
                  "x":570,
                  "y":420},
                "size":{
                  "width":300,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b26b152639224a2b9e297df24c613cbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSansMedium', 'Fira Sans Medium', 'Fira Sans'",
            "fontSize":"15px",
            "location":{
              "x":570,
              "y":760},
            "size":{
              "width":300,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fef3493dd0d34cf2be929a11c7f21cf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSansMedium', 'Fira Sans Medium', 'Fira Sans'",
                "fontSize":"15px",
                "location":{
                  "x":570,
                  "y":760},
                "size":{
                  "width":300,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0303d4d614d9444bade4713fa03393d5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":820},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/2a_screenshot/u16_line.png"}},
{
          "id":"1d5feb9bb45d4eba8ee7cbec7a76a030",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":975},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/2a_screenshot/u16_line.png"}},
{
          "id":"7eb88f77eb2f40c9a45a0465b7eb859b",
          "label":"description",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":448},
            "size":{
              "width":300,
              "height":240}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"30eaf3d446e44fcd9e21063d9bb5d7ec",
              "label":"blank",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e32eab54275345e784798d14202f3c23",
                  "label":"description text",
                  "parentDynamicPanel":"7eb88f77eb2f40c9a45a0465b7eb859b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "fontSize":"28px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
}},
                    "size":{
                      "width":300,
                      "height":240},
                    "borderWidth":"2",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dd47dc2936724966aab481e253294611",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7eb88f77eb2f40c9a45a0465b7eb859b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans', 'Fira Sans'",
                        "fontSize":"28px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
}},
                        "size":{
                          "width":300,
                          "height":240},
                        "borderWidth":"2",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set description to onclick",
                              "panelsToStates":[{
                                  "panelPath":["7eb88f77eb2f40c9a45a0465b7eb859b"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/2a_screenshot/description_text_u104.png"}},
{
                  "id":"e5876f24111445ddb6b42b20d6723f2c",
                  "label":"",
                  "parentDynamicPanel":"7eb88f77eb2f40c9a45a0465b7eb859b",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":136,
                      "y":106},
                    "size":{
                      "width":28,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7aa4c649c62945e1a2e794aa26a488ae",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7eb88f77eb2f40c9a45a0465b7eb859b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":136,
                          "y":106},
                        "size":{
                          "width":28,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set description to onclick",
                              "panelsToStates":[{
                                  "panelPath":["7eb88f77eb2f40c9a45a0465b7eb859b"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/2a_screenshot/u106.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"69461b98dae24f28bc17af8d1e788c59",
              "label":"onclick",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"390fc63b352a46a9b6f557c5c8be048d",
                  "label":"description textbox",
                  "parentDynamicPanel":"7eb88f77eb2f40c9a45a0465b7eb859b",
                  "panelIndex":1,
                  "type":"textArea",
                  "styleType":"textArea",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "size":{
                      "width":300,
                      "height":205}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onKeyUp":{
                      "description":"OnKeyUp",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"Set text on description text equal to text on This",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetRichText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["214fc9245a53471f8ef748821f48bc57"]},
{
                                        "exprType":"fcall",
                                        "functionName":"GetWidgetText",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":true,
                                            "isFocused":false,
                                            "isTarget":false}]},
{
                                        "exprType":"booleanLiteral",
                                        "value":true}]}]}}]}]}}},
{
                  "id":"11ebb18e5b8f41b1a40db3f8d1e8eac9",
                  "label":"",
                  "parentDynamicPanel":"7eb88f77eb2f40c9a45a0465b7eb859b",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFF4CB1FF},
{
                          "color":0xFF4CB1FF},
{
                          "color":0xFF1793E5},
{
                          "color":0xFF1793E5}]},
                    "location":{
                      "x":250,
                      "y":215},
                    "size":{
                      "width":50,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF1793E5},
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"28cee987ccc4456da9dbec71e12ef505",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7eb88f77eb2f40c9a45a0465b7eb859b",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans', 'Fira Sans'",
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFF4CB1FF},
{
                              "color":0xFF4CB1FF},
{
                              "color":0xFF1793E5},
{
                              "color":0xFF1793E5}]},
                        "location":{
                          "x":250,
                          "y":215},
                        "size":{
                          "width":50,
                          "height":25},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF1793E5},
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open 2c support email in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"2c_support_email.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/2b_description/u24.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"9baa267099d94b669c2bb63adf5b1bf1",
              "label":"edited",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ff5c5d64465d49a9bfb3c459d66f27f0",
                  "label":"description text",
                  "parentDynamicPanel":"7eb88f77eb2f40c9a45a0465b7eb859b",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'FiraSans', 'Fira Sans'",
                    "fontSize":"15px",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFFCC}}},
                    "size":{
                      "width":300,
                      "height":240}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"214fc9245a53471f8ef748821f48bc57",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7eb88f77eb2f40c9a45a0465b7eb859b",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'FiraSans', 'Fira Sans'",
                        "fontSize":"15px",
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFFCC}}},
                        "size":{
                          "width":300,
                          "height":240}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set description to onclick",
                              "panelsToStates":[{
                                  "panelPath":["7eb88f77eb2f40c9a45a0465b7eb859b"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"images/2b_description/description_text_u26_mouseOver.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"df5b81ef986b48b581f12cc2a2d7bbd1",
          "label":"name text",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'FiraSansLight', 'Fira Sans Light', 'Fira Sans'",
            "fontSize":"20px",
            "fontWeight":"200",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":650,
              "y":97},
            "size":{
              "width":220,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59b36864034b44b4921ce8b2ea2dadd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSansLight', 'Fira Sans Light', 'Fira Sans'",
                "fontSize":"20px",
                "fontWeight":"200",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":650,
                  "y":97},
                "size":{
                  "width":220,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e68680f030ca4714842ad8200d43edce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":575,
              "y":95},
            "size":{
              "width":64,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f875b1a11354f4586bdaef2bba456a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":575,
                  "y":95},
                "size":{
                  "width":64,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u20.png"}},
{
          "id":"11f5fc7c989a43b5b9d5d8eed5812bb0",
          "label":"icon-tooltip",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":656,
              "y":405},
            "size":{
              "width":148,
              "height":64},
            "cornerRadiusTopLeft":"5",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baef7ecc5932471f8c8dce9f8df85e7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":656,
                  "y":405},
                "size":{
                  "width":148,
                  "height":64},
                "cornerRadiusTopLeft":"5",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/icon-tooltip_u89.png"}},
{
          "id":"108691eec90a48c69879914d465f1068",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":210},
            "size":{
              "width":100,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3be6ea0755a4065b869b282ec69e696",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":210},
                "size":{
                  "width":100,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u74.png"}},
{
          "id":"9b4def7424924870a1c0e1ce82fa2e77",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":210},
            "size":{
              "width":100,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67b3edbd4f8a4a3f9b6b178830329442",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":670,
                  "y":210},
                "size":{
                  "width":100,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u50.png"}},
{
          "id":"9b8ee346119d4abea976bef3aa07cf57",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":210},
            "size":{
              "width":100,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"211ecc63a650458d9c1b0e0785df3951",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":210},
                "size":{
                  "width":100,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u32.png"}},
{
          "id":"91a0d55d31ba4c3eae5dd9122a320afd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":714,
              "y":375},
            "size":{
              "width":13,
              "height":13},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c57a13f7ff04749b78b46b2f091cf7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":714,
                  "y":375},
                "size":{
                  "width":13,
                  "height":13},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u94.png"}},
{
          "id":"b098b8e6fa334697a4b4e471e9e3ed04",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":734,
              "y":375},
            "size":{
              "width":13,
              "height":13},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaba149b870a4786998bfca5a3ba9b01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":734,
                  "y":375},
                "size":{
                  "width":13,
                  "height":13},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u94.png"}},
{
          "id":"cf3d0eb6411a4cd2bcd63af2b55ba3fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":694,
              "y":375},
            "size":{
              "width":13,
              "height":13},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3ce96e8df464bb3bc221dd7c33b2d01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":694,
                  "y":375},
                "size":{
                  "width":13,
                  "height":13},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u92.png"}},
{
          "id":"2617971309db44cd95bb67735a5683a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":570,
              "y":850},
            "size":{
              "width":145,
              "height":45},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "linePattern":"dashed",
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e98630d05aa4879a74d0c05ebdb306d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":570,
                  "y":850},
                "size":{
                  "width":145,
                  "height":45},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "linePattern":"dashed",
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u108.png"}},
{
          "id":"bbd99f1ec3a34d82a5e848fe83e80d9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":725,
              "y":850},
            "size":{
              "width":145,
              "height":45},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "linePattern":"dashed",
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca345abbb0044e79aee92817ffb8df4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":725,
                  "y":850},
                "size":{
                  "width":145,
                  "height":45},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "linePattern":"dashed",
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u108.png"}},
{
          "id":"3ba3037d9fc541a582ce8c36f123aa5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":570,
              "y":910},
            "size":{
              "width":145,
              "height":45},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "linePattern":"dashed",
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e96c5abb4df54fe1b8e54ab75ef3a099",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":570,
                  "y":910},
                "size":{
                  "width":145,
                  "height":45},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "linePattern":"dashed",
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u108.png"}},
{
          "id":"dc010ec4684d436589fb7dd19c109d31",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":725,
              "y":910},
            "size":{
              "width":145,
              "height":45},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "linePattern":"dashed",
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc4d7dceb4b54bfda9bb14896b1a453d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":725,
                  "y":910},
                "size":{
                  "width":145,
                  "height":45},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "linePattern":"dashed",
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u108.png"}},
{
          "id":"41f2bbc85bfe4503bff7d2422a96e0a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":692,
              "y":875},
            "size":{
              "width":56,
              "height":56},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE7E7E7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fd9f2fd1e0e4a9b95454cad21f8602b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":692,
                  "y":875},
                "size":{
                  "width":56,
                  "height":56},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE7E7E7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u116.png"}},
{
          "id":"3ea867e15e6541328dd599f54372a969",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":706,
              "y":889},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cab04fad78349e4acd30bfb79d6127a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":706,
                  "y":889},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u106.png"}},
{
          "id":"1a61b2f31a684330aa33837bc7cebf88",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "location":{
              "x":320,
              "y":80},
            "size":{
              "width":220,
              "height":135},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "linePattern":"none",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03b17b86e7a44e25955d6683c27e4fc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "location":{
                  "x":320,
                  "y":80},
                "size":{
                  "width":220,
                  "height":135},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "linePattern":"none",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u120.png"}},
{
          "id":"c657bc69259245c2965680464469cd5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":130},
            "size":{
              "width":220,
              "height":40},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8d97c86d51540c6b979c1929c8f4df5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":130},
                "size":{
                  "width":220,
                  "height":40},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u122.png"}},
{
          "id":"08e85ad884ef4d0eb5ae81b319c11501",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":125},
            "size":{
              "width":220,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/2a_screenshot/u124_line.png"}},
{
          "id":"4d75119da15b4dd787051ab5a26e6c8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":335,
              "y":140},
            "size":{
              "width":45,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab553f05e5fd41a091334e900e2c8371",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":335,
                  "y":140},
                "size":{
                  "width":45,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30ef20d3d413473481173361480ec13e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"11px",
            "horizontalAlignment":"right",
            "location":{
              "x":488,
              "y":142},
            "size":{
              "width":37,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"292d9b4b97854540808eb1cfe463d59e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"11px",
                "horizontalAlignment":"right",
                "location":{
                  "x":488,
                  "y":142},
                "size":{
                  "width":37,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29cd69999c584872a9be1cbbc0ef7ae3",
          "label":"description text",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":570,
              "y":700},
            "size":{
              "width":300,
              "height":50},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77122ebba80b4f2fa0820dd782301da5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":570,
                  "y":700},
                "size":{
                  "width":300,
                  "height":50},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/description_text_u129.png"}},
{
          "id":"7ee95fa7412e454ba8f7c636e72d2f52",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":706,
              "y":711},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bb5b741de744b2ea9f5dfa7340dc0ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":706,
                  "y":711},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u106.png"}},
{
          "id":"bd18bd85079d4aabbebdc7042a1acf5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":645,
              "y":713},
            "size":{
              "width":53,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"015912f3ade141ec88be682c0ba50120",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":645,
                  "y":713},
                "size":{
                  "width":53,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"902a087b5a6e47b9859d4b7bbe4fa7c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":743,
              "y":713},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4461f916e8994419a4f7c99f1783ef42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":743,
                  "y":713},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98f8248d9d71494eab98908c8fc529cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSansMedium', 'Fira Sans Medium', 'Fira Sans'",
            "fontSize":"15px",
            "fontWeight":"500",
            "location":{
              "x":335,
              "y":95},
            "size":{
              "width":74,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd1b7a4b1e8f467cb888b62cc1af8644",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSansMedium', 'Fira Sans Medium', 'Fira Sans'",
                "fontSize":"15px",
                "fontWeight":"500",
                "location":{
                  "x":335,
                  "y":95},
                "size":{
                  "width":74,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7b356bba69047b4b066531d92eac814",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":335,
              "y":180},
            "size":{
              "width":103,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6890aeb8e7ed443887283569bfe805ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":335,
                  "y":180},
                "size":{
                  "width":103,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"edd77f810e4a4c3fbb73e3ffbd79f514",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE7E7E7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFC7C7C7},
            "location":{
              "x":718,
              "y":1255},
            "size":{
              "width":160,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA7A7A7},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce8f5a42ceb6431fb05ce1c8dadf636c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE7E7E7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC7C7C7},
                "location":{
                  "x":718,
                  "y":1255},
                "size":{
                  "width":160,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA7A7A7},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u141.png"}},
{
          "id":"4e89dd0b0f82431a9a4e0f1567a922b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF4CB1FF},
{
                  "color":0xFF4CB1FF},
{
                  "color":0xFF1793E5},
{
                  "color":0xFF1793E5}]},
            "location":{
              "x":320,
              "y":1255},
            "size":{
              "width":160,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF1793E5},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66de79b197be4a168f0f7da7a482c8ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF4CB1FF},
{
                      "color":0xFF4CB1FF},
{
                      "color":0xFF1793E5},
{
                      "color":0xFF1793E5}]},
                "location":{
                  "x":320,
                  "y":1255},
                "size":{
                  "width":160,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF1793E5},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 1 upload manifest in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"1_upload_manifest.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/2a_screenshot/u143.png"}},
{
          "id":"709f3c43ea3d420e9b0e6e92d096f508",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "location":{
              "x":80,
              "y":80},
            "size":{
              "width":220,
              "height":320},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "linePattern":"none",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"facdce7acb784b16b10300da1e38074d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "location":{
                  "x":80,
                  "y":80},
                "size":{
                  "width":220,
                  "height":320},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "linePattern":"none",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_upload_manifest/u6.png"}},
{
          "id":"019160f5e217468c85249b1aec5ef3dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":120},
            "size":{
              "width":220,
              "height":40},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2529063f07d04bb6b7dbcf083d05296d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":120},
                "size":{
                  "width":220,
                  "height":40},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2a_screenshot/u122.png"}},
{
          "id":"f90be5a8766a4916bc7e80fa2f7c61ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":90},
            "size":{
              "width":52,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7dcf192c8564d4699073929dd9c1300",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":90},
                "size":{
                  "width":52,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"933ebdb70bf4415e872799f8962b97ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":130},
            "size":{
              "width":122,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"236c9d77b2a44c1fb58892bcf968cc5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":130},
                "size":{
                  "width":122,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cff1d3daa83543de93a852635d27ceb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":170},
            "size":{
              "width":64,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ee7ced2e45a4b28acb98517a394719a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":170},
                "size":{
                  "width":64,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87d069eea0f94eecaf2455c926e3e9a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":210},
            "size":{
              "width":133,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bd8ebaa7e0545a8a8973a2b49cbcde5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":210},
                "size":{
                  "width":133,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"835d84afdcc8428f9f40d8888227d47e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":250},
            "size":{
              "width":91,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"040ad7d93776408493308baeffbf08f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":250},
                "size":{
                  "width":91,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5cf55b7198824575b818952a2a4fa23d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":330},
            "size":{
              "width":128,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"924b4b6c8a564ae0b984a87614c5a67b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":330},
                "size":{
                  "width":128,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"468d8dac1dc24d02ad29e83637defdae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":370},
            "size":{
              "width":80,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93b834e04ed243eeac65b69857c99ae9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":370},
                "size":{
                  "width":80,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"618efc98055545fba6e5d8f4b7e68bf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":95,
              "y":290},
            "size":{
              "width":46,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80ac6bfe54324432b6f1eb4617f4cef8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":95,
                  "y":290},
                "size":{
                  "width":46,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81e298b0dd0a40f186ba4c6acec825fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'FiraSans', 'Fira Sans'",
            "location":{
              "x":80,
              "y":30},
            "size":{
              "width":232,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51f7a0ecbf79401bab621a298dc73459",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'FiraSans', 'Fira Sans'",
                "location":{
                  "x":80,
                  "y":30},
                "size":{
                  "width":232,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 9 my submissions in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"9_my_submissions.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "068958af0f4a497a9237fab6b8a2abc0":{
      "scriptId":"u0"},
    "afbd9078f47e46038c0a9b30d33e2b96":{
      "scriptId":"u1"},
    "240845c1c5ec497bae383ef3ca257183":{
      "scriptId":"u2"},
    "6cbf4b1302d54c30b9f1336c1a79b264":{
      "scriptId":"u3"},
    "f32859cf52494a8baf0d2ed7a42c16ab":{
      "scriptId":"u4"},
    "3f8eb2c37a31462589c5fc390bd404ea":{
      "scriptId":"u5"},
    "b144a4fb0ac14ff39f2c83ece7200767":{
      "scriptId":"u6"},
    "e622920565d84ae2ab6da890378ed0e6":{
      "scriptId":"u7"},
    "2d9c6a2021bd4bc4baabfb914bf7645e":{
      "scriptId":"u8"},
    "e4fb28d747db4018a896bc301899d246":{
      "scriptId":"u9"},
    "255d878e864a4762b2f564aa723c2871":{
      "scriptId":"u10"},
    "b139eafafc534e4582ef8580adcbfac0":{
      "scriptId":"u11"},
    "8580e2a4213549eb83500888a1d2c7dd":{
      "scriptId":"u12"},
    "67e8d18e30f14b09b2812b29914bc7ad":{
      "scriptId":"u13"},
    "b26b152639224a2b9e297df24c613cbd":{
      "scriptId":"u14"},
    "fef3493dd0d34cf2be929a11c7f21cf3":{
      "scriptId":"u15"},
    "0303d4d614d9444bade4713fa03393d5":{
      "scriptId":"u16"},
    "1d5feb9bb45d4eba8ee7cbec7a76a030":{
      "scriptId":"u17"},
    "7eb88f77eb2f40c9a45a0465b7eb859b":{
      "scriptId":"u18"},
    "e32eab54275345e784798d14202f3c23":{
      "scriptId":"u19"},
    "dd47dc2936724966aab481e253294611":{
      "scriptId":"u20"},
    "e5876f24111445ddb6b42b20d6723f2c":{
      "scriptId":"u21"},
    "7aa4c649c62945e1a2e794aa26a488ae":{
      "scriptId":"u22"},
    "390fc63b352a46a9b6f557c5c8be048d":{
      "scriptId":"u23"},
    "11ebb18e5b8f41b1a40db3f8d1e8eac9":{
      "scriptId":"u24"},
    "28cee987ccc4456da9dbec71e12ef505":{
      "scriptId":"u25"},
    "ff5c5d64465d49a9bfb3c459d66f27f0":{
      "scriptId":"u26"},
    "214fc9245a53471f8ef748821f48bc57":{
      "scriptId":"u27"},
    "df5b81ef986b48b581f12cc2a2d7bbd1":{
      "scriptId":"u28"},
    "59b36864034b44b4921ce8b2ea2dadd0":{
      "scriptId":"u29"},
    "e68680f030ca4714842ad8200d43edce":{
      "scriptId":"u30"},
    "4f875b1a11354f4586bdaef2bba456a6":{
      "scriptId":"u31"},
    "11f5fc7c989a43b5b9d5d8eed5812bb0":{
      "scriptId":"u32"},
    "baef7ecc5932471f8c8dce9f8df85e7b":{
      "scriptId":"u33"},
    "108691eec90a48c69879914d465f1068":{
      "scriptId":"u34"},
    "b3be6ea0755a4065b869b282ec69e696":{
      "scriptId":"u35"},
    "9b4def7424924870a1c0e1ce82fa2e77":{
      "scriptId":"u36"},
    "67b3edbd4f8a4a3f9b6b178830329442":{
      "scriptId":"u37"},
    "9b8ee346119d4abea976bef3aa07cf57":{
      "scriptId":"u38"},
    "211ecc63a650458d9c1b0e0785df3951":{
      "scriptId":"u39"},
    "91a0d55d31ba4c3eae5dd9122a320afd":{
      "scriptId":"u40"},
    "5c57a13f7ff04749b78b46b2f091cf7e":{
      "scriptId":"u41"},
    "b098b8e6fa334697a4b4e471e9e3ed04":{
      "scriptId":"u42"},
    "eaba149b870a4786998bfca5a3ba9b01":{
      "scriptId":"u43"},
    "cf3d0eb6411a4cd2bcd63af2b55ba3fd":{
      "scriptId":"u44"},
    "c3ce96e8df464bb3bc221dd7c33b2d01":{
      "scriptId":"u45"},
    "2617971309db44cd95bb67735a5683a9":{
      "scriptId":"u46"},
    "5e98630d05aa4879a74d0c05ebdb306d":{
      "scriptId":"u47"},
    "bbd99f1ec3a34d82a5e848fe83e80d9f":{
      "scriptId":"u48"},
    "ca345abbb0044e79aee92817ffb8df4d":{
      "scriptId":"u49"},
    "3ba3037d9fc541a582ce8c36f123aa5b":{
      "scriptId":"u50"},
    "e96c5abb4df54fe1b8e54ab75ef3a099":{
      "scriptId":"u51"},
    "dc010ec4684d436589fb7dd19c109d31":{
      "scriptId":"u52"},
    "bc4d7dceb4b54bfda9bb14896b1a453d":{
      "scriptId":"u53"},
    "41f2bbc85bfe4503bff7d2422a96e0a5":{
      "scriptId":"u54"},
    "5fd9f2fd1e0e4a9b95454cad21f8602b":{
      "scriptId":"u55"},
    "3ea867e15e6541328dd599f54372a969":{
      "scriptId":"u56"},
    "7cab04fad78349e4acd30bfb79d6127a":{
      "scriptId":"u57"},
    "1a61b2f31a684330aa33837bc7cebf88":{
      "scriptId":"u58"},
    "03b17b86e7a44e25955d6683c27e4fc3":{
      "scriptId":"u59"},
    "c657bc69259245c2965680464469cd5c":{
      "scriptId":"u60"},
    "b8d97c86d51540c6b979c1929c8f4df5":{
      "scriptId":"u61"},
    "08e85ad884ef4d0eb5ae81b319c11501":{
      "scriptId":"u62"},
    "4d75119da15b4dd787051ab5a26e6c8b":{
      "scriptId":"u63"},
    "ab553f05e5fd41a091334e900e2c8371":{
      "scriptId":"u64"},
    "30ef20d3d413473481173361480ec13e":{
      "scriptId":"u65"},
    "292d9b4b97854540808eb1cfe463d59e":{
      "scriptId":"u66"},
    "29cd69999c584872a9be1cbbc0ef7ae3":{
      "scriptId":"u67"},
    "77122ebba80b4f2fa0820dd782301da5":{
      "scriptId":"u68"},
    "7ee95fa7412e454ba8f7c636e72d2f52":{
      "scriptId":"u69"},
    "5bb5b741de744b2ea9f5dfa7340dc0ce":{
      "scriptId":"u70"},
    "bd18bd85079d4aabbebdc7042a1acf5b":{
      "scriptId":"u71"},
    "015912f3ade141ec88be682c0ba50120":{
      "scriptId":"u72"},
    "902a087b5a6e47b9859d4b7bbe4fa7c2":{
      "scriptId":"u73"},
    "4461f916e8994419a4f7c99f1783ef42":{
      "scriptId":"u74"},
    "98f8248d9d71494eab98908c8fc529cc":{
      "scriptId":"u75"},
    "cd1b7a4b1e8f467cb888b62cc1af8644":{
      "scriptId":"u76"},
    "c7b356bba69047b4b066531d92eac814":{
      "scriptId":"u77"},
    "6890aeb8e7ed443887283569bfe805ef":{
      "scriptId":"u78"},
    "edd77f810e4a4c3fbb73e3ffbd79f514":{
      "scriptId":"u79"},
    "ce8f5a42ceb6431fb05ce1c8dadf636c":{
      "scriptId":"u80"},
    "4e89dd0b0f82431a9a4e0f1567a922b4":{
      "scriptId":"u81"},
    "66de79b197be4a168f0f7da7a482c8ff":{
      "scriptId":"u82"},
    "709f3c43ea3d420e9b0e6e92d096f508":{
      "scriptId":"u83"},
    "facdce7acb784b16b10300da1e38074d":{
      "scriptId":"u84"},
    "019160f5e217468c85249b1aec5ef3dc":{
      "scriptId":"u85"},
    "2529063f07d04bb6b7dbcf083d05296d":{
      "scriptId":"u86"},
    "f90be5a8766a4916bc7e80fa2f7c61ae":{
      "scriptId":"u87"},
    "c7dcf192c8564d4699073929dd9c1300":{
      "scriptId":"u88"},
    "933ebdb70bf4415e872799f8962b97ee":{
      "scriptId":"u89"},
    "236c9d77b2a44c1fb58892bcf968cc5f":{
      "scriptId":"u90"},
    "cff1d3daa83543de93a852635d27ceb7":{
      "scriptId":"u91"},
    "5ee7ced2e45a4b28acb98517a394719a":{
      "scriptId":"u92"},
    "87d069eea0f94eecaf2455c926e3e9a7":{
      "scriptId":"u93"},
    "3bd8ebaa7e0545a8a8973a2b49cbcde5":{
      "scriptId":"u94"},
    "835d84afdcc8428f9f40d8888227d47e":{
      "scriptId":"u95"},
    "040ad7d93776408493308baeffbf08f0":{
      "scriptId":"u96"},
    "5cf55b7198824575b818952a2a4fa23d":{
      "scriptId":"u97"},
    "924b4b6c8a564ae0b984a87614c5a67b":{
      "scriptId":"u98"},
    "468d8dac1dc24d02ad29e83637defdae":{
      "scriptId":"u99"},
    "93b834e04ed243eeac65b69857c99ae9":{
      "scriptId":"u100"},
    "618efc98055545fba6e5d8f4b7e68bf6":{
      "scriptId":"u101"},
    "80ac6bfe54324432b6f1eb4617f4cef8":{
      "scriptId":"u102"},
    "81e298b0dd0a40f186ba4c6acec825fe":{
      "scriptId":"u103"},
    "51f7a0ecbf79401bab621a298dc73459":{
      "scriptId":"u104"}}});